// Code generated by ent, DO NOT EDIT.

package imagejobinput

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldJobID, v))
}

// Index applies equality check predicate on the "index" field. It's identical to IndexEQ.
func Index(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldIndex, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldKind, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldObjectKey, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldMimeType, v))
}

// ByteSize applies equality check predicate on the "byte_size" field. It's identical to ByteSizeEQ.
func ByteSize(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldByteSize, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldCreatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldJobID, vs...))
}

// IndexEQ applies the EQ predicate on the "index" field.
func IndexEQ(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldIndex, v))
}

// IndexNEQ applies the NEQ predicate on the "index" field.
func IndexNEQ(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldIndex, v))
}

// IndexIn applies the In predicate on the "index" field.
func IndexIn(vs ...int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldIndex, vs...))
}

// IndexNotIn applies the NotIn predicate on the "index" field.
func IndexNotIn(vs ...int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldIndex, vs...))
}

// IndexGT applies the GT predicate on the "index" field.
func IndexGT(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldIndex, v))
}

// IndexGTE applies the GTE predicate on the "index" field.
func IndexGTE(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldIndex, v))
}

// IndexLT applies the LT predicate on the "index" field.
func IndexLT(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldIndex, v))
}

// IndexLTE applies the LTE predicate on the "index" field.
func IndexLTE(v int) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldIndex, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContainsFold(FieldKind, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContainsFold(FieldObjectKey, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContainsFold(FieldMimeType, v))
}

// ByteSizeEQ applies the EQ predicate on the "byte_size" field.
func ByteSizeEQ(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldByteSize, v))
}

// ByteSizeNEQ applies the NEQ predicate on the "byte_size" field.
func ByteSizeNEQ(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldByteSize, v))
}

// ByteSizeIn applies the In predicate on the "byte_size" field.
func ByteSizeIn(vs ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldByteSize, vs...))
}

// ByteSizeNotIn applies the NotIn predicate on the "byte_size" field.
func ByteSizeNotIn(vs ...int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldByteSize, vs...))
}

// ByteSizeGT applies the GT predicate on the "byte_size" field.
func ByteSizeGT(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldByteSize, v))
}

// ByteSizeGTE applies the GTE predicate on the "byte_size" field.
func ByteSizeGTE(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldByteSize, v))
}

// ByteSizeLT applies the LT predicate on the "byte_size" field.
func ByteSizeLT(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldByteSize, v))
}

// ByteSizeLTE applies the LTE predicate on the "byte_size" field.
func ByteSizeLTE(v int64) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldByteSize, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldContainsFold(FieldSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.FieldLTE(FieldCreatedAt, v))
}

// HasJob applies the HasEdge predicate on the "job" edge.
func HasJob() predicate.ImageJobInput {
	return predicate.ImageJobInput(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobWith applies the HasEdge predicate on the "job" edge with a given conditions (other predicates).
func HasJobWith(preds ...predicate.ImageJob) predicate.ImageJobInput {
	return predicate.ImageJobInput(func(s *sql.Selector) {
		step := newJobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageJobInput) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageJobInput) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageJobInput) predicate.ImageJobInput {
	return predicate.ImageJobInput(sql.NotPredicates(p))
}
