// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobresult"
)

// ImageJobResultCreate is the builder for creating a ImageJobResult entity.
type ImageJobResultCreate struct {
	config
	mutation *ImageJobResultMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageJobResultCreate) SetCreatedAt(v time.Time) *ImageJobResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableCreatedAt(v *time.Time) *ImageJobResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageJobResultCreate) SetUpdatedAt(v time.Time) *ImageJobResultCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableUpdatedAt(v *time.Time) *ImageJobResultCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *ImageJobResultCreate) SetJobID(v int64) *ImageJobResultCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetIndex sets the "index" field.
func (_c *ImageJobResultCreate) SetIndex(v int) *ImageJobResultCreate {
	_c.mutation.SetIndex(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImageJobResultCreate) SetStatus(v string) *ImageJobResultCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *ImageJobResultCreate) SetObjectKey(v string) *ImageJobResultCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableObjectKey(v *string) *ImageJobResultCreate {
	if v != nil {
		_c.SetObjectKey(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ImageJobResultCreate) SetMimeType(v string) *ImageJobResultCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableMimeType(v *string) *ImageJobResultCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *ImageJobResultCreate) SetByteSize(v int64) *ImageJobResultCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableByteSize(v *int64) *ImageJobResultCreate {
	if v != nil {
		_c.SetByteSize(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageJobResultCreate) SetWidth(v int) *ImageJobResultCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableWidth(v *int) *ImageJobResultCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageJobResultCreate) SetHeight(v int) *ImageJobResultCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableHeight(v *int) *ImageJobResultCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetSizeTier sets the "size_tier" field.
func (_c *ImageJobResultCreate) SetSizeTier(v string) *ImageJobResultCreate {
	_c.mutation.SetSizeTier(v)
	return _c
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableSizeTier(v *string) *ImageJobResultCreate {
	if v != nil {
		_c.SetSizeTier(*v)
	}
	return _c
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_c *ImageJobResultCreate) SetRevisedPrompt(v string) *ImageJobResultCreate {
	_c.mutation.SetRevisedPrompt(v)
	return _c
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableRevisedPrompt(v *string) *ImageJobResultCreate {
	if v != nil {
		_c.SetRevisedPrompt(*v)
	}
	return _c
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (_c *ImageJobResultCreate) SetUpstreamOutputID(v string) *ImageJobResultCreate {
	_c.mutation.SetUpstreamOutputID(v)
	return _c
}

// SetNillableUpstreamOutputID sets the "upstream_output_id" field if the given value is not nil.
func (_c *ImageJobResultCreate) SetNillableUpstreamOutputID(v *string) *ImageJobResultCreate {
	if v != nil {
		_c.SetUpstreamOutputID(*v)
	}
	return _c
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_c *ImageJobResultCreate) SetJob(v *ImageJob) *ImageJobResultCreate {
	return _c.SetJobID(v.ID)
}

// Mutation returns the ImageJobResultMutation object of the builder.
func (_c *ImageJobResultCreate) Mutation() *ImageJobResultMutation {
	return _c.mutation
}

// Save creates the ImageJobResult in the database.
func (_c *ImageJobResultCreate) Save(ctx context.Context) (*ImageJobResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageJobResultCreate) SaveX(ctx context.Context) *ImageJobResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageJobResultCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagejobresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imagejobresult.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageJobResultCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageJobResult.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageJobResult.updated_at"`)}
	}
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "ImageJobResult.job_id"`)}
	}
	if _, ok := _c.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`ent: missing required field "ImageJobResult.index"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImageJobResult.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imagejobresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := imagejobresult.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.mime_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SizeTier(); ok {
		if err := imagejobresult.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.size_tier": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamOutputID(); ok {
		if err := imagejobresult.UpstreamOutputIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_output_id", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.upstream_output_id": %w`, err)}
		}
	}
	if len(_c.mutation.JobIDs()) == 0 {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required edge "ImageJobResult.job"`)}
	}
	return nil
}

func (_c *ImageJobResultCreate) sqlSave(ctx context.Context) (*ImageJobResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageJobResultCreate) createSpec() (*ImageJobResult, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageJobResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagejobresult.Table, sqlgraph.NewFieldSpec(imagejobresult.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagejobresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imagejobresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Index(); ok {
		_spec.SetField(imagejobresult.FieldIndex, field.TypeInt, value)
		_node.Index = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imagejobresult.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobresult.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = &value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(imagejobresult.FieldMimeType, field.TypeString, value)
		_node.MimeType = &value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(imagejobresult.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = &value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(imagejobresult.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(imagejobresult.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.SizeTier(); ok {
		_spec.SetField(imagejobresult.FieldSizeTier, field.TypeString, value)
		_node.SizeTier = &value
	}
	if value, ok := _c.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagejobresult.FieldRevisedPrompt, field.TypeString, value)
		_node.RevisedPrompt = &value
	}
	if value, ok := _c.mutation.UpstreamOutputID(); ok {
		_spec.SetField(imagejobresult.FieldUpstreamOutputID, field.TypeString, value)
		_node.UpstreamOutputID = &value
	}
	if nodes := _c.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobresult.JobTable,
			Columns: []string{imagejobresult.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJobResult.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobResultUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobResultCreate) OnConflict(opts ...sql.ConflictOption) *ImageJobResultUpsertOne {
	_c.conflict = opts
	return &ImageJobResultUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobResultCreate) OnConflictColumns(columns ...string) *ImageJobResultUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobResultUpsertOne{
		create: _c,
	}
}

type (
	// ImageJobResultUpsertOne is the builder for "upsert"-ing
	//  one ImageJobResult node.
	ImageJobResultUpsertOne struct {
		create *ImageJobResultCreate
	}

	// ImageJobResultUpsert is the "OnConflict" setter.
	ImageJobResultUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobResultUpsert) SetUpdatedAt(v time.Time) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateUpdatedAt() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldUpdatedAt)
	return u
}

// SetJobID sets the "job_id" field.
func (u *ImageJobResultUpsert) SetJobID(v int64) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateJobID() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldJobID)
	return u
}

// SetIndex sets the "index" field.
func (u *ImageJobResultUpsert) SetIndex(v int) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldIndex, v)
	return u
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateIndex() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldIndex)
	return u
}

// AddIndex adds v to the "index" field.
func (u *ImageJobResultUpsert) AddIndex(v int) *ImageJobResultUpsert {
	u.Add(imagejobresult.FieldIndex, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ImageJobResultUpsert) SetStatus(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateStatus() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldStatus)
	return u
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobResultUpsert) SetObjectKey(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldObjectKey, v)
	return u
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateObjectKey() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldObjectKey)
	return u
}

// ClearObjectKey clears the value of the "object_key" field.
func (u *ImageJobResultUpsert) ClearObjectKey() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldObjectKey)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobResultUpsert) SetMimeType(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateMimeType() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldMimeType)
	return u
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *ImageJobResultUpsert) ClearMimeType() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldMimeType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobResultUpsert) SetByteSize(v int64) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateByteSize() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobResultUpsert) AddByteSize(v int64) *ImageJobResultUpsert {
	u.Add(imagejobresult.FieldByteSize, v)
	return u
}

// ClearByteSize clears the value of the "byte_size" field.
func (u *ImageJobResultUpsert) ClearByteSize() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldByteSize)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageJobResultUpsert) SetWidth(v int) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateWidth() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageJobResultUpsert) AddWidth(v int) *ImageJobResultUpsert {
	u.Add(imagejobresult.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *ImageJobResultUpsert) ClearWidth() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageJobResultUpsert) SetHeight(v int) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateHeight() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageJobResultUpsert) AddHeight(v int) *ImageJobResultUpsert {
	u.Add(imagejobresult.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *ImageJobResultUpsert) ClearHeight() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldHeight)
	return u
}

// SetSizeTier sets the "size_tier" field.
func (u *ImageJobResultUpsert) SetSizeTier(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldSizeTier, v)
	return u
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateSizeTier() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldSizeTier)
	return u
}

// ClearSizeTier clears the value of the "size_tier" field.
func (u *ImageJobResultUpsert) ClearSizeTier() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldSizeTier)
	return u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageJobResultUpsert) SetRevisedPrompt(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldRevisedPrompt, v)
	return u
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateRevisedPrompt() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldRevisedPrompt)
	return u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageJobResultUpsert) ClearRevisedPrompt() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldRevisedPrompt)
	return u
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (u *ImageJobResultUpsert) SetUpstreamOutputID(v string) *ImageJobResultUpsert {
	u.Set(imagejobresult.FieldUpstreamOutputID, v)
	return u
}

// UpdateUpstreamOutputID sets the "upstream_output_id" field to the value that was provided on create.
func (u *ImageJobResultUpsert) UpdateUpstreamOutputID() *ImageJobResultUpsert {
	u.SetExcluded(imagejobresult.FieldUpstreamOutputID)
	return u
}

// ClearUpstreamOutputID clears the value of the "upstream_output_id" field.
func (u *ImageJobResultUpsert) ClearUpstreamOutputID() *ImageJobResultUpsert {
	u.SetNull(imagejobresult.FieldUpstreamOutputID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobResultUpsertOne) UpdateNewValues() *ImageJobResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagejobresult.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageJobResultUpsertOne) Ignore() *ImageJobResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobResultUpsertOne) DoNothing() *ImageJobResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobResultCreate.OnConflict
// documentation for more info.
func (u *ImageJobResultUpsertOne) Update(set func(*ImageJobResultUpsert)) *ImageJobResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobResultUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobResultUpsertOne) SetUpdatedAt(v time.Time) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateUpdatedAt() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetJobID sets the "job_id" field.
func (u *ImageJobResultUpsertOne) SetJobID(v int64) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateJobID() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateJobID()
	})
}

// SetIndex sets the "index" field.
func (u *ImageJobResultUpsertOne) SetIndex(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageJobResultUpsertOne) AddIndex(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateIndex() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateIndex()
	})
}

// SetStatus sets the "status" field.
func (u *ImageJobResultUpsertOne) SetStatus(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateStatus() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateStatus()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobResultUpsertOne) SetObjectKey(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateObjectKey() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateObjectKey()
	})
}

// ClearObjectKey clears the value of the "object_key" field.
func (u *ImageJobResultUpsertOne) ClearObjectKey() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearObjectKey()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobResultUpsertOne) SetMimeType(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateMimeType() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *ImageJobResultUpsertOne) ClearMimeType() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearMimeType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobResultUpsertOne) SetByteSize(v int64) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobResultUpsertOne) AddByteSize(v int64) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateByteSize() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateByteSize()
	})
}

// ClearByteSize clears the value of the "byte_size" field.
func (u *ImageJobResultUpsertOne) ClearByteSize() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearByteSize()
	})
}

// SetWidth sets the "width" field.
func (u *ImageJobResultUpsertOne) SetWidth(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageJobResultUpsertOne) AddWidth(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateWidth() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *ImageJobResultUpsertOne) ClearWidth() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageJobResultUpsertOne) SetHeight(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageJobResultUpsertOne) AddHeight(v int) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateHeight() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *ImageJobResultUpsertOne) ClearHeight() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearHeight()
	})
}

// SetSizeTier sets the "size_tier" field.
func (u *ImageJobResultUpsertOne) SetSizeTier(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetSizeTier(v)
	})
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateSizeTier() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateSizeTier()
	})
}

// ClearSizeTier clears the value of the "size_tier" field.
func (u *ImageJobResultUpsertOne) ClearSizeTier() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearSizeTier()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageJobResultUpsertOne) SetRevisedPrompt(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateRevisedPrompt() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageJobResultUpsertOne) ClearRevisedPrompt() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (u *ImageJobResultUpsertOne) SetUpstreamOutputID(v string) *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetUpstreamOutputID(v)
	})
}

// UpdateUpstreamOutputID sets the "upstream_output_id" field to the value that was provided on create.
func (u *ImageJobResultUpsertOne) UpdateUpstreamOutputID() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateUpstreamOutputID()
	})
}

// ClearUpstreamOutputID clears the value of the "upstream_output_id" field.
func (u *ImageJobResultUpsertOne) ClearUpstreamOutputID() *ImageJobResultUpsertOne {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearUpstreamOutputID()
	})
}

// Exec executes the query.
func (u *ImageJobResultUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobResultCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobResultUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageJobResultUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageJobResultUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageJobResultCreateBulk is the builder for creating many ImageJobResult entities in bulk.
type ImageJobResultCreateBulk struct {
	config
	err      error
	builders []*ImageJobResultCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageJobResult entities in the database.
func (_c *ImageJobResultCreateBulk) Save(ctx context.Context) ([]*ImageJobResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageJobResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageJobResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageJobResultCreateBulk) SaveX(ctx context.Context) []*ImageJobResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJobResult.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobResultUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobResultCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageJobResultUpsertBulk {
	_c.conflict = opts
	return &ImageJobResultUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobResultCreateBulk) OnConflictColumns(columns ...string) *ImageJobResultUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobResultUpsertBulk{
		create: _c,
	}
}

// ImageJobResultUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageJobResult nodes.
type ImageJobResultUpsertBulk struct {
	create *ImageJobResultCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobResultUpsertBulk) UpdateNewValues() *ImageJobResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagejobresult.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJobResult.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageJobResultUpsertBulk) Ignore() *ImageJobResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobResultUpsertBulk) DoNothing() *ImageJobResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobResultCreateBulk.OnConflict
// documentation for more info.
func (u *ImageJobResultUpsertBulk) Update(set func(*ImageJobResultUpsert)) *ImageJobResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobResultUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobResultUpsertBulk) SetUpdatedAt(v time.Time) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateUpdatedAt() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetJobID sets the "job_id" field.
func (u *ImageJobResultUpsertBulk) SetJobID(v int64) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateJobID() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateJobID()
	})
}

// SetIndex sets the "index" field.
func (u *ImageJobResultUpsertBulk) SetIndex(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageJobResultUpsertBulk) AddIndex(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateIndex() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateIndex()
	})
}

// SetStatus sets the "status" field.
func (u *ImageJobResultUpsertBulk) SetStatus(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateStatus() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateStatus()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobResultUpsertBulk) SetObjectKey(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateObjectKey() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateObjectKey()
	})
}

// ClearObjectKey clears the value of the "object_key" field.
func (u *ImageJobResultUpsertBulk) ClearObjectKey() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearObjectKey()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobResultUpsertBulk) SetMimeType(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateMimeType() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *ImageJobResultUpsertBulk) ClearMimeType() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearMimeType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobResultUpsertBulk) SetByteSize(v int64) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobResultUpsertBulk) AddByteSize(v int64) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateByteSize() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateByteSize()
	})
}

// ClearByteSize clears the value of the "byte_size" field.
func (u *ImageJobResultUpsertBulk) ClearByteSize() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearByteSize()
	})
}

// SetWidth sets the "width" field.
func (u *ImageJobResultUpsertBulk) SetWidth(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageJobResultUpsertBulk) AddWidth(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateWidth() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *ImageJobResultUpsertBulk) ClearWidth() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageJobResultUpsertBulk) SetHeight(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageJobResultUpsertBulk) AddHeight(v int) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateHeight() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *ImageJobResultUpsertBulk) ClearHeight() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearHeight()
	})
}

// SetSizeTier sets the "size_tier" field.
func (u *ImageJobResultUpsertBulk) SetSizeTier(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetSizeTier(v)
	})
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateSizeTier() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateSizeTier()
	})
}

// ClearSizeTier clears the value of the "size_tier" field.
func (u *ImageJobResultUpsertBulk) ClearSizeTier() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearSizeTier()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageJobResultUpsertBulk) SetRevisedPrompt(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateRevisedPrompt() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageJobResultUpsertBulk) ClearRevisedPrompt() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (u *ImageJobResultUpsertBulk) SetUpstreamOutputID(v string) *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.SetUpstreamOutputID(v)
	})
}

// UpdateUpstreamOutputID sets the "upstream_output_id" field to the value that was provided on create.
func (u *ImageJobResultUpsertBulk) UpdateUpstreamOutputID() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.UpdateUpstreamOutputID()
	})
}

// ClearUpstreamOutputID clears the value of the "upstream_output_id" field.
func (u *ImageJobResultUpsertBulk) ClearUpstreamOutputID() *ImageJobResultUpsertBulk {
	return u.Update(func(s *ImageJobResultUpsert) {
		s.ClearUpstreamOutputID()
	})
}

// Exec executes the query.
func (u *ImageJobResultUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageJobResultCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobResultCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobResultUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
