// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobinput"
)

// ImageJobInputCreate is the builder for creating a ImageJobInput entity.
type ImageJobInputCreate struct {
	config
	mutation *ImageJobInputMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJobID sets the "job_id" field.
func (_c *ImageJobInputCreate) SetJobID(v int64) *ImageJobInputCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetIndex sets the "index" field.
func (_c *ImageJobInputCreate) SetIndex(v int) *ImageJobInputCreate {
	_c.mutation.SetIndex(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ImageJobInputCreate) SetKind(v string) *ImageJobInputCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *ImageJobInputCreate) SetObjectKey(v string) *ImageJobInputCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ImageJobInputCreate) SetMimeType(v string) *ImageJobInputCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *ImageJobInputCreate) SetByteSize(v int64) *ImageJobInputCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ImageJobInputCreate) SetSha256(v string) *ImageJobInputCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageJobInputCreate) SetCreatedAt(v time.Time) *ImageJobInputCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageJobInputCreate) SetNillableCreatedAt(v *time.Time) *ImageJobInputCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_c *ImageJobInputCreate) SetJob(v *ImageJob) *ImageJobInputCreate {
	return _c.SetJobID(v.ID)
}

// Mutation returns the ImageJobInputMutation object of the builder.
func (_c *ImageJobInputCreate) Mutation() *ImageJobInputMutation {
	return _c.mutation
}

// Save creates the ImageJobInput in the database.
func (_c *ImageJobInputCreate) Save(ctx context.Context) (*ImageJobInput, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageJobInputCreate) SaveX(ctx context.Context) *ImageJobInput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobInputCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobInputCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageJobInputCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagejobinput.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageJobInputCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "ImageJobInput.job_id"`)}
	}
	if _, ok := _c.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`ent: missing required field "ImageJobInput.index"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ImageJobInput.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := imagejobinput.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "ImageJobInput.object_key"`)}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "ImageJobInput.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := imagejobinput.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "ImageJobInput.byte_size"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "ImageJobInput.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := imagejobinput.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageJobInput.created_at"`)}
	}
	if len(_c.mutation.JobIDs()) == 0 {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required edge "ImageJobInput.job"`)}
	}
	return nil
}

func (_c *ImageJobInputCreate) sqlSave(ctx context.Context) (*ImageJobInput, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageJobInputCreate) createSpec() (*ImageJobInput, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageJobInput{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagejobinput.Table, sqlgraph.NewFieldSpec(imagejobinput.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Index(); ok {
		_spec.SetField(imagejobinput.FieldIndex, field.TypeInt, value)
		_node.Index = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(imagejobinput.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobinput.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(imagejobinput.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(imagejobinput.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(imagejobinput.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagejobinput.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobinput.JobTable,
			Columns: []string{imagejobinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJobInput.Create().
//		SetJobID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobInputUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobInputCreate) OnConflict(opts ...sql.ConflictOption) *ImageJobInputUpsertOne {
	_c.conflict = opts
	return &ImageJobInputUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobInputCreate) OnConflictColumns(columns ...string) *ImageJobInputUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobInputUpsertOne{
		create: _c,
	}
}

type (
	// ImageJobInputUpsertOne is the builder for "upsert"-ing
	//  one ImageJobInput node.
	ImageJobInputUpsertOne struct {
		create *ImageJobInputCreate
	}

	// ImageJobInputUpsert is the "OnConflict" setter.
	ImageJobInputUpsert struct {
		*sql.UpdateSet
	}
)

// SetJobID sets the "job_id" field.
func (u *ImageJobInputUpsert) SetJobID(v int64) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateJobID() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldJobID)
	return u
}

// SetIndex sets the "index" field.
func (u *ImageJobInputUpsert) SetIndex(v int) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldIndex, v)
	return u
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateIndex() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldIndex)
	return u
}

// AddIndex adds v to the "index" field.
func (u *ImageJobInputUpsert) AddIndex(v int) *ImageJobInputUpsert {
	u.Add(imagejobinput.FieldIndex, v)
	return u
}

// SetKind sets the "kind" field.
func (u *ImageJobInputUpsert) SetKind(v string) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateKind() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldKind)
	return u
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobInputUpsert) SetObjectKey(v string) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldObjectKey, v)
	return u
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateObjectKey() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldObjectKey)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobInputUpsert) SetMimeType(v string) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateMimeType() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldMimeType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobInputUpsert) SetByteSize(v int64) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateByteSize() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobInputUpsert) AddByteSize(v int64) *ImageJobInputUpsert {
	u.Add(imagejobinput.FieldByteSize, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *ImageJobInputUpsert) SetSha256(v string) *ImageJobInputUpsert {
	u.Set(imagejobinput.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageJobInputUpsert) UpdateSha256() *ImageJobInputUpsert {
	u.SetExcluded(imagejobinput.FieldSha256)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobInputUpsertOne) UpdateNewValues() *ImageJobInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagejobinput.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageJobInputUpsertOne) Ignore() *ImageJobInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobInputUpsertOne) DoNothing() *ImageJobInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobInputCreate.OnConflict
// documentation for more info.
func (u *ImageJobInputUpsertOne) Update(set func(*ImageJobInputUpsert)) *ImageJobInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobInputUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *ImageJobInputUpsertOne) SetJobID(v int64) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateJobID() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateJobID()
	})
}

// SetIndex sets the "index" field.
func (u *ImageJobInputUpsertOne) SetIndex(v int) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageJobInputUpsertOne) AddIndex(v int) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateIndex() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateIndex()
	})
}

// SetKind sets the "kind" field.
func (u *ImageJobInputUpsertOne) SetKind(v string) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateKind() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateKind()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobInputUpsertOne) SetObjectKey(v string) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateObjectKey() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateObjectKey()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobInputUpsertOne) SetMimeType(v string) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateMimeType() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateMimeType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobInputUpsertOne) SetByteSize(v int64) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobInputUpsertOne) AddByteSize(v int64) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateByteSize() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageJobInputUpsertOne) SetSha256(v string) *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageJobInputUpsertOne) UpdateSha256() *ImageJobInputUpsertOne {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *ImageJobInputUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobInputCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobInputUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageJobInputUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageJobInputUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageJobInputCreateBulk is the builder for creating many ImageJobInput entities in bulk.
type ImageJobInputCreateBulk struct {
	config
	err      error
	builders []*ImageJobInputCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageJobInput entities in the database.
func (_c *ImageJobInputCreateBulk) Save(ctx context.Context) ([]*ImageJobInput, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageJobInput, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageJobInputMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageJobInputCreateBulk) SaveX(ctx context.Context) []*ImageJobInput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobInputCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobInputCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJobInput.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobInputUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobInputCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageJobInputUpsertBulk {
	_c.conflict = opts
	return &ImageJobInputUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobInputCreateBulk) OnConflictColumns(columns ...string) *ImageJobInputUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobInputUpsertBulk{
		create: _c,
	}
}

// ImageJobInputUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageJobInput nodes.
type ImageJobInputUpsertBulk struct {
	create *ImageJobInputCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobInputUpsertBulk) UpdateNewValues() *ImageJobInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagejobinput.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJobInput.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageJobInputUpsertBulk) Ignore() *ImageJobInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobInputUpsertBulk) DoNothing() *ImageJobInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobInputCreateBulk.OnConflict
// documentation for more info.
func (u *ImageJobInputUpsertBulk) Update(set func(*ImageJobInputUpsert)) *ImageJobInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobInputUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *ImageJobInputUpsertBulk) SetJobID(v int64) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateJobID() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateJobID()
	})
}

// SetIndex sets the "index" field.
func (u *ImageJobInputUpsertBulk) SetIndex(v int) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageJobInputUpsertBulk) AddIndex(v int) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateIndex() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateIndex()
	})
}

// SetKind sets the "kind" field.
func (u *ImageJobInputUpsertBulk) SetKind(v string) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateKind() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateKind()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *ImageJobInputUpsertBulk) SetObjectKey(v string) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateObjectKey() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateObjectKey()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageJobInputUpsertBulk) SetMimeType(v string) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateMimeType() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateMimeType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageJobInputUpsertBulk) SetByteSize(v int64) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageJobInputUpsertBulk) AddByteSize(v int64) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateByteSize() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageJobInputUpsertBulk) SetSha256(v string) *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageJobInputUpsertBulk) UpdateSha256() *ImageJobInputUpsertBulk {
	return u.Update(func(s *ImageJobInputUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *ImageJobInputUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageJobInputCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobInputCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobInputUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
