// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobresult"
)

// ImageJobResult is the model entity for the ImageJobResult schema.
type ImageJobResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID int64 `json:"job_id,omitempty"`
	// Index holds the value of the "index" field.
	Index int `json:"index,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey *string `json:"object_key,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType *string `json:"mime_type,omitempty"`
	// ByteSize holds the value of the "byte_size" field.
	ByteSize *int64 `json:"byte_size,omitempty"`
	// Width holds the value of the "width" field.
	Width *int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height *int `json:"height,omitempty"`
	// SizeTier holds the value of the "size_tier" field.
	SizeTier *string `json:"size_tier,omitempty"`
	// RevisedPrompt holds the value of the "revised_prompt" field.
	RevisedPrompt *string `json:"revised_prompt,omitempty"`
	// UpstreamOutputID holds the value of the "upstream_output_id" field.
	UpstreamOutputID *string `json:"upstream_output_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageJobResultQuery when eager-loading is set.
	Edges        ImageJobResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageJobResultEdges holds the relations/edges for other nodes in the graph.
type ImageJobResultEdges struct {
	// Job holds the value of the job edge.
	Job *ImageJob `json:"job,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageJobResultEdges) JobOrErr() (*ImageJob, error) {
	if e.Job != nil {
		return e.Job, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imagejob.Label}
	}
	return nil, &NotLoadedError{edge: "job"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageJobResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagejobresult.FieldID, imagejobresult.FieldJobID, imagejobresult.FieldIndex, imagejobresult.FieldByteSize, imagejobresult.FieldWidth, imagejobresult.FieldHeight:
			values[i] = new(sql.NullInt64)
		case imagejobresult.FieldStatus, imagejobresult.FieldObjectKey, imagejobresult.FieldMimeType, imagejobresult.FieldSizeTier, imagejobresult.FieldRevisedPrompt, imagejobresult.FieldUpstreamOutputID:
			values[i] = new(sql.NullString)
		case imagejobresult.FieldCreatedAt, imagejobresult.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageJobResult fields.
func (_m *ImageJobResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagejobresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagejobresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagejobresult.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagejobresult.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.Int64
			}
		case imagejobresult.FieldIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index", values[i])
			} else if value.Valid {
				_m.Index = int(value.Int64)
			}
		case imagejobresult.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imagejobresult.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = new(string)
				*_m.ObjectKey = value.String
			}
		case imagejobresult.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = new(string)
				*_m.MimeType = value.String
			}
		case imagejobresult.FieldByteSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_size", values[i])
			} else if value.Valid {
				_m.ByteSize = new(int64)
				*_m.ByteSize = value.Int64
			}
		case imagejobresult.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(int)
				*_m.Width = int(value.Int64)
			}
		case imagejobresult.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = new(int)
				*_m.Height = int(value.Int64)
			}
		case imagejobresult.FieldSizeTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size_tier", values[i])
			} else if value.Valid {
				_m.SizeTier = new(string)
				*_m.SizeTier = value.String
			}
		case imagejobresult.FieldRevisedPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revised_prompt", values[i])
			} else if value.Valid {
				_m.RevisedPrompt = new(string)
				*_m.RevisedPrompt = value.String
			}
		case imagejobresult.FieldUpstreamOutputID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_output_id", values[i])
			} else if value.Valid {
				_m.UpstreamOutputID = new(string)
				*_m.UpstreamOutputID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageJobResult.
// This includes values selected through modifiers, order, etc.
func (_m *ImageJobResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJob queries the "job" edge of the ImageJobResult entity.
func (_m *ImageJobResult) QueryJob() *ImageJobQuery {
	return NewImageJobResultClient(_m.config).QueryJob(_m)
}

// Update returns a builder for updating this ImageJobResult.
// Note that you need to call ImageJobResult.Unwrap() before calling this method if this ImageJobResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageJobResult) Update() *ImageJobResultUpdateOne {
	return NewImageJobResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageJobResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageJobResult) Unwrap() *ImageJobResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageJobResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageJobResult) String() string {
	var builder strings.Builder
	builder.WriteString("ImageJobResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("index=")
	builder.WriteString(fmt.Sprintf("%v", _m.Index))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ObjectKey; v != nil {
		builder.WriteString("object_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MimeType; v != nil {
		builder.WriteString("mime_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ByteSize; v != nil {
		builder.WriteString("byte_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SizeTier; v != nil {
		builder.WriteString("size_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RevisedPrompt; v != nil {
		builder.WriteString("revised_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamOutputID; v != nil {
		builder.WriteString("upstream_output_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImageJobResults is a parsable slice of ImageJobResult.
type ImageJobResults []*ImageJobResult
