// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejobresult"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageJobResultDelete is the builder for deleting a ImageJobResult entity.
type ImageJobResultDelete struct {
	config
	hooks    []Hook
	mutation *ImageJobResultMutation
}

// Where appends a list predicates to the ImageJobResultDelete builder.
func (_d *ImageJobResultDelete) Where(ps ...predicate.ImageJobResult) *ImageJobResultDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ImageJobResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageJobResultDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ImageJobResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(imagejobresult.Table, sqlgraph.NewFieldSpec(imagejobresult.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ImageJobResultDeleteOne is the builder for deleting a single ImageJobResult entity.
type ImageJobResultDeleteOne struct {
	_d *ImageJobResultDelete
}

// Where appends a list predicates to the ImageJobResultDelete builder.
func (_d *ImageJobResultDeleteOne) Where(ps ...predicate.ImageJobResult) *ImageJobResultDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ImageJobResultDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{imagejobresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageJobResultDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
