// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobresult"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageJobResultUpdate is the builder for updating ImageJobResult entities.
type ImageJobResultUpdate struct {
	config
	hooks    []Hook
	mutation *ImageJobResultMutation
}

// Where appends a list predicates to the ImageJobResultUpdate builder.
func (_u *ImageJobResultUpdate) Where(ps ...predicate.ImageJobResult) *ImageJobResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageJobResultUpdate) SetUpdatedAt(v time.Time) *ImageJobResultUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *ImageJobResultUpdate) SetJobID(v int64) *ImageJobResultUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableJobID(v *int64) *ImageJobResultUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetIndex sets the "index" field.
func (_u *ImageJobResultUpdate) SetIndex(v int) *ImageJobResultUpdate {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableIndex(v *int) *ImageJobResultUpdate {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *ImageJobResultUpdate) AddIndex(v int) *ImageJobResultUpdate {
	_u.mutation.AddIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageJobResultUpdate) SetStatus(v string) *ImageJobResultUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableStatus(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *ImageJobResultUpdate) SetObjectKey(v string) *ImageJobResultUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableObjectKey(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// ClearObjectKey clears the value of the "object_key" field.
func (_u *ImageJobResultUpdate) ClearObjectKey() *ImageJobResultUpdate {
	_u.mutation.ClearObjectKey()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageJobResultUpdate) SetMimeType(v string) *ImageJobResultUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableMimeType(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ImageJobResultUpdate) ClearMimeType() *ImageJobResultUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageJobResultUpdate) SetByteSize(v int64) *ImageJobResultUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableByteSize(v *int64) *ImageJobResultUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageJobResultUpdate) AddByteSize(v int64) *ImageJobResultUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// ClearByteSize clears the value of the "byte_size" field.
func (_u *ImageJobResultUpdate) ClearByteSize() *ImageJobResultUpdate {
	_u.mutation.ClearByteSize()
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageJobResultUpdate) SetWidth(v int) *ImageJobResultUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableWidth(v *int) *ImageJobResultUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageJobResultUpdate) AddWidth(v int) *ImageJobResultUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *ImageJobResultUpdate) ClearWidth() *ImageJobResultUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageJobResultUpdate) SetHeight(v int) *ImageJobResultUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableHeight(v *int) *ImageJobResultUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageJobResultUpdate) AddHeight(v int) *ImageJobResultUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *ImageJobResultUpdate) ClearHeight() *ImageJobResultUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *ImageJobResultUpdate) SetSizeTier(v string) *ImageJobResultUpdate {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableSizeTier(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// ClearSizeTier clears the value of the "size_tier" field.
func (_u *ImageJobResultUpdate) ClearSizeTier() *ImageJobResultUpdate {
	_u.mutation.ClearSizeTier()
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageJobResultUpdate) SetRevisedPrompt(v string) *ImageJobResultUpdate {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableRevisedPrompt(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *ImageJobResultUpdate) ClearRevisedPrompt() *ImageJobResultUpdate {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (_u *ImageJobResultUpdate) SetUpstreamOutputID(v string) *ImageJobResultUpdate {
	_u.mutation.SetUpstreamOutputID(v)
	return _u
}

// SetNillableUpstreamOutputID sets the "upstream_output_id" field if the given value is not nil.
func (_u *ImageJobResultUpdate) SetNillableUpstreamOutputID(v *string) *ImageJobResultUpdate {
	if v != nil {
		_u.SetUpstreamOutputID(*v)
	}
	return _u
}

// ClearUpstreamOutputID clears the value of the "upstream_output_id" field.
func (_u *ImageJobResultUpdate) ClearUpstreamOutputID() *ImageJobResultUpdate {
	_u.mutation.ClearUpstreamOutputID()
	return _u
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_u *ImageJobResultUpdate) SetJob(v *ImageJob) *ImageJobResultUpdate {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImageJobResultMutation object of the builder.
func (_u *ImageJobResultUpdate) Mutation() *ImageJobResultMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImageJob entity.
func (_u *ImageJobResultUpdate) ClearJob() *ImageJobResultUpdate {
	_u.mutation.ClearJob()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageJobResultUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageJobResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageJobResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageJobResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageJobResultUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagejobresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageJobResultUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := imagejobresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagejobresult.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := imagejobresult.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.size_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamOutputID(); ok {
		if err := imagejobresult.UpstreamOutputIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_output_id", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.upstream_output_id": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageJobResult.job"`)
	}
	return nil
}

func (_u *ImageJobResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagejobresult.Table, imagejobresult.Columns, sqlgraph.NewFieldSpec(imagejobresult.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagejobresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(imagejobresult.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(imagejobresult.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagejobresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobresult.FieldObjectKey, field.TypeString, value)
	}
	if _u.mutation.ObjectKeyCleared() {
		_spec.ClearField(imagejobresult.FieldObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagejobresult.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(imagejobresult.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagejobresult.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagejobresult.FieldByteSize, field.TypeInt64, value)
	}
	if _u.mutation.ByteSizeCleared() {
		_spec.ClearField(imagejobresult.FieldByteSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagejobresult.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagejobresult.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(imagejobresult.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagejobresult.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagejobresult.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(imagejobresult.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(imagejobresult.FieldSizeTier, field.TypeString, value)
	}
	if _u.mutation.SizeTierCleared() {
		_spec.ClearField(imagejobresult.FieldSizeTier, field.TypeString)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagejobresult.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(imagejobresult.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamOutputID(); ok {
		_spec.SetField(imagejobresult.FieldUpstreamOutputID, field.TypeString, value)
	}
	if _u.mutation.UpstreamOutputIDCleared() {
		_spec.ClearField(imagejobresult.FieldUpstreamOutputID, field.TypeString)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobresult.JobTable,
			Columns: []string{imagejobresult.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobresult.JobTable,
			Columns: []string{imagejobresult.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagejobresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageJobResultUpdateOne is the builder for updating a single ImageJobResult entity.
type ImageJobResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageJobResultMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageJobResultUpdateOne) SetUpdatedAt(v time.Time) *ImageJobResultUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *ImageJobResultUpdateOne) SetJobID(v int64) *ImageJobResultUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableJobID(v *int64) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetIndex sets the "index" field.
func (_u *ImageJobResultUpdateOne) SetIndex(v int) *ImageJobResultUpdateOne {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableIndex(v *int) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *ImageJobResultUpdateOne) AddIndex(v int) *ImageJobResultUpdateOne {
	_u.mutation.AddIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageJobResultUpdateOne) SetStatus(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableStatus(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *ImageJobResultUpdateOne) SetObjectKey(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableObjectKey(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// ClearObjectKey clears the value of the "object_key" field.
func (_u *ImageJobResultUpdateOne) ClearObjectKey() *ImageJobResultUpdateOne {
	_u.mutation.ClearObjectKey()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageJobResultUpdateOne) SetMimeType(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableMimeType(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ImageJobResultUpdateOne) ClearMimeType() *ImageJobResultUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageJobResultUpdateOne) SetByteSize(v int64) *ImageJobResultUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableByteSize(v *int64) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageJobResultUpdateOne) AddByteSize(v int64) *ImageJobResultUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// ClearByteSize clears the value of the "byte_size" field.
func (_u *ImageJobResultUpdateOne) ClearByteSize() *ImageJobResultUpdateOne {
	_u.mutation.ClearByteSize()
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageJobResultUpdateOne) SetWidth(v int) *ImageJobResultUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableWidth(v *int) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageJobResultUpdateOne) AddWidth(v int) *ImageJobResultUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *ImageJobResultUpdateOne) ClearWidth() *ImageJobResultUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageJobResultUpdateOne) SetHeight(v int) *ImageJobResultUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableHeight(v *int) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageJobResultUpdateOne) AddHeight(v int) *ImageJobResultUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *ImageJobResultUpdateOne) ClearHeight() *ImageJobResultUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *ImageJobResultUpdateOne) SetSizeTier(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableSizeTier(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// ClearSizeTier clears the value of the "size_tier" field.
func (_u *ImageJobResultUpdateOne) ClearSizeTier() *ImageJobResultUpdateOne {
	_u.mutation.ClearSizeTier()
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageJobResultUpdateOne) SetRevisedPrompt(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableRevisedPrompt(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *ImageJobResultUpdateOne) ClearRevisedPrompt() *ImageJobResultUpdateOne {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetUpstreamOutputID sets the "upstream_output_id" field.
func (_u *ImageJobResultUpdateOne) SetUpstreamOutputID(v string) *ImageJobResultUpdateOne {
	_u.mutation.SetUpstreamOutputID(v)
	return _u
}

// SetNillableUpstreamOutputID sets the "upstream_output_id" field if the given value is not nil.
func (_u *ImageJobResultUpdateOne) SetNillableUpstreamOutputID(v *string) *ImageJobResultUpdateOne {
	if v != nil {
		_u.SetUpstreamOutputID(*v)
	}
	return _u
}

// ClearUpstreamOutputID clears the value of the "upstream_output_id" field.
func (_u *ImageJobResultUpdateOne) ClearUpstreamOutputID() *ImageJobResultUpdateOne {
	_u.mutation.ClearUpstreamOutputID()
	return _u
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_u *ImageJobResultUpdateOne) SetJob(v *ImageJob) *ImageJobResultUpdateOne {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImageJobResultMutation object of the builder.
func (_u *ImageJobResultUpdateOne) Mutation() *ImageJobResultMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImageJob entity.
func (_u *ImageJobResultUpdateOne) ClearJob() *ImageJobResultUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// Where appends a list predicates to the ImageJobResultUpdate builder.
func (_u *ImageJobResultUpdateOne) Where(ps ...predicate.ImageJobResult) *ImageJobResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageJobResultUpdateOne) Select(field string, fields ...string) *ImageJobResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageJobResult entity.
func (_u *ImageJobResultUpdateOne) Save(ctx context.Context) (*ImageJobResult, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageJobResultUpdateOne) SaveX(ctx context.Context) *ImageJobResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageJobResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageJobResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageJobResultUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagejobresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageJobResultUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := imagejobresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagejobresult.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := imagejobresult.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.size_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamOutputID(); ok {
		if err := imagejobresult.UpstreamOutputIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_output_id", err: fmt.Errorf(`ent: validator failed for field "ImageJobResult.upstream_output_id": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageJobResult.job"`)
	}
	return nil
}

func (_u *ImageJobResultUpdateOne) sqlSave(ctx context.Context) (_node *ImageJobResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagejobresult.Table, imagejobresult.Columns, sqlgraph.NewFieldSpec(imagejobresult.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageJobResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagejobresult.FieldID)
		for _, f := range fields {
			if !imagejobresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagejobresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagejobresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(imagejobresult.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(imagejobresult.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagejobresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobresult.FieldObjectKey, field.TypeString, value)
	}
	if _u.mutation.ObjectKeyCleared() {
		_spec.ClearField(imagejobresult.FieldObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagejobresult.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(imagejobresult.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagejobresult.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagejobresult.FieldByteSize, field.TypeInt64, value)
	}
	if _u.mutation.ByteSizeCleared() {
		_spec.ClearField(imagejobresult.FieldByteSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagejobresult.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagejobresult.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(imagejobresult.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagejobresult.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagejobresult.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(imagejobresult.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(imagejobresult.FieldSizeTier, field.TypeString, value)
	}
	if _u.mutation.SizeTierCleared() {
		_spec.ClearField(imagejobresult.FieldSizeTier, field.TypeString)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagejobresult.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(imagejobresult.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamOutputID(); ok {
		_spec.SetField(imagejobresult.FieldUpstreamOutputID, field.TypeString, value)
	}
	if _u.mutation.UpstreamOutputIDCleared() {
		_spec.ClearField(imagejobresult.FieldUpstreamOutputID, field.TypeString)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobresult.JobTable,
			Columns: []string{imagejobresult.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobresult.JobTable,
			Columns: []string{imagejobresult.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageJobResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagejobresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
