// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobinput"
)

// ImageJobInput is the model entity for the ImageJobInput schema.
type ImageJobInput struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID int64 `json:"job_id,omitempty"`
	// Index holds the value of the "index" field.
	Index int `json:"index,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// ByteSize holds the value of the "byte_size" field.
	ByteSize int64 `json:"byte_size,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageJobInputQuery when eager-loading is set.
	Edges        ImageJobInputEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageJobInputEdges holds the relations/edges for other nodes in the graph.
type ImageJobInputEdges struct {
	// Job holds the value of the job edge.
	Job *ImageJob `json:"job,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageJobInputEdges) JobOrErr() (*ImageJob, error) {
	if e.Job != nil {
		return e.Job, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imagejob.Label}
	}
	return nil, &NotLoadedError{edge: "job"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageJobInput) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagejobinput.FieldID, imagejobinput.FieldJobID, imagejobinput.FieldIndex, imagejobinput.FieldByteSize:
			values[i] = new(sql.NullInt64)
		case imagejobinput.FieldKind, imagejobinput.FieldObjectKey, imagejobinput.FieldMimeType, imagejobinput.FieldSha256:
			values[i] = new(sql.NullString)
		case imagejobinput.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageJobInput fields.
func (_m *ImageJobInput) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagejobinput.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagejobinput.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.Int64
			}
		case imagejobinput.FieldIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index", values[i])
			} else if value.Valid {
				_m.Index = int(value.Int64)
			}
		case imagejobinput.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case imagejobinput.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case imagejobinput.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case imagejobinput.FieldByteSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_size", values[i])
			} else if value.Valid {
				_m.ByteSize = value.Int64
			}
		case imagejobinput.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case imagejobinput.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageJobInput.
// This includes values selected through modifiers, order, etc.
func (_m *ImageJobInput) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJob queries the "job" edge of the ImageJobInput entity.
func (_m *ImageJobInput) QueryJob() *ImageJobQuery {
	return NewImageJobInputClient(_m.config).QueryJob(_m)
}

// Update returns a builder for updating this ImageJobInput.
// Note that you need to call ImageJobInput.Unwrap() before calling this method if this ImageJobInput
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageJobInput) Update() *ImageJobInputUpdateOne {
	return NewImageJobInputClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageJobInput entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageJobInput) Unwrap() *ImageJobInput {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageJobInput is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageJobInput) String() string {
	var builder strings.Builder
	builder.WriteString("ImageJobInput(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("index=")
	builder.WriteString(fmt.Sprintf("%v", _m.Index))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("byte_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteSize))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageJobInputs is a parsable slice of ImageJobInput.
type ImageJobInputs []*ImageJobInput
