// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobinput"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageJobInputUpdate is the builder for updating ImageJobInput entities.
type ImageJobInputUpdate struct {
	config
	hooks    []Hook
	mutation *ImageJobInputMutation
}

// Where appends a list predicates to the ImageJobInputUpdate builder.
func (_u *ImageJobInputUpdate) Where(ps ...predicate.ImageJobInput) *ImageJobInputUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *ImageJobInputUpdate) SetJobID(v int64) *ImageJobInputUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableJobID(v *int64) *ImageJobInputUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetIndex sets the "index" field.
func (_u *ImageJobInputUpdate) SetIndex(v int) *ImageJobInputUpdate {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableIndex(v *int) *ImageJobInputUpdate {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *ImageJobInputUpdate) AddIndex(v int) *ImageJobInputUpdate {
	_u.mutation.AddIndex(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *ImageJobInputUpdate) SetKind(v string) *ImageJobInputUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableKind(v *string) *ImageJobInputUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *ImageJobInputUpdate) SetObjectKey(v string) *ImageJobInputUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableObjectKey(v *string) *ImageJobInputUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageJobInputUpdate) SetMimeType(v string) *ImageJobInputUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableMimeType(v *string) *ImageJobInputUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageJobInputUpdate) SetByteSize(v int64) *ImageJobInputUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableByteSize(v *int64) *ImageJobInputUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageJobInputUpdate) AddByteSize(v int64) *ImageJobInputUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageJobInputUpdate) SetSha256(v string) *ImageJobInputUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageJobInputUpdate) SetNillableSha256(v *string) *ImageJobInputUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_u *ImageJobInputUpdate) SetJob(v *ImageJob) *ImageJobInputUpdate {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImageJobInputMutation object of the builder.
func (_u *ImageJobInputUpdate) Mutation() *ImageJobInputMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImageJob entity.
func (_u *ImageJobInputUpdate) ClearJob() *ImageJobInputUpdate {
	_u.mutation.ClearJob()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageJobInputUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageJobInputUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageJobInputUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageJobInputUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageJobInputUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := imagejobinput.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagejobinput.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imagejobinput.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.sha256": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageJobInput.job"`)
	}
	return nil
}

func (_u *ImageJobInputUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagejobinput.Table, imagejobinput.Columns, sqlgraph.NewFieldSpec(imagejobinput.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(imagejobinput.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(imagejobinput.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(imagejobinput.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobinput.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagejobinput.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagejobinput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagejobinput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imagejobinput.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobinput.JobTable,
			Columns: []string{imagejobinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobinput.JobTable,
			Columns: []string{imagejobinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagejobinput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageJobInputUpdateOne is the builder for updating a single ImageJobInput entity.
type ImageJobInputUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageJobInputMutation
}

// SetJobID sets the "job_id" field.
func (_u *ImageJobInputUpdateOne) SetJobID(v int64) *ImageJobInputUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableJobID(v *int64) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetIndex sets the "index" field.
func (_u *ImageJobInputUpdateOne) SetIndex(v int) *ImageJobInputUpdateOne {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableIndex(v *int) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *ImageJobInputUpdateOne) AddIndex(v int) *ImageJobInputUpdateOne {
	_u.mutation.AddIndex(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *ImageJobInputUpdateOne) SetKind(v string) *ImageJobInputUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableKind(v *string) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *ImageJobInputUpdateOne) SetObjectKey(v string) *ImageJobInputUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableObjectKey(v *string) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageJobInputUpdateOne) SetMimeType(v string) *ImageJobInputUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableMimeType(v *string) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageJobInputUpdateOne) SetByteSize(v int64) *ImageJobInputUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableByteSize(v *int64) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageJobInputUpdateOne) AddByteSize(v int64) *ImageJobInputUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageJobInputUpdateOne) SetSha256(v string) *ImageJobInputUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageJobInputUpdateOne) SetNillableSha256(v *string) *ImageJobInputUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetJob sets the "job" edge to the ImageJob entity.
func (_u *ImageJobInputUpdateOne) SetJob(v *ImageJob) *ImageJobInputUpdateOne {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImageJobInputMutation object of the builder.
func (_u *ImageJobInputUpdateOne) Mutation() *ImageJobInputMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImageJob entity.
func (_u *ImageJobInputUpdateOne) ClearJob() *ImageJobInputUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// Where appends a list predicates to the ImageJobInputUpdate builder.
func (_u *ImageJobInputUpdateOne) Where(ps ...predicate.ImageJobInput) *ImageJobInputUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageJobInputUpdateOne) Select(field string, fields ...string) *ImageJobInputUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageJobInput entity.
func (_u *ImageJobInputUpdateOne) Save(ctx context.Context) (*ImageJobInput, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageJobInputUpdateOne) SaveX(ctx context.Context) *ImageJobInput {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageJobInputUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageJobInputUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageJobInputUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := imagejobinput.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagejobinput.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imagejobinput.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageJobInput.sha256": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageJobInput.job"`)
	}
	return nil
}

func (_u *ImageJobInputUpdateOne) sqlSave(ctx context.Context) (_node *ImageJobInput, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagejobinput.Table, imagejobinput.Columns, sqlgraph.NewFieldSpec(imagejobinput.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageJobInput.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagejobinput.FieldID)
		for _, f := range fields {
			if !imagejobinput.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagejobinput.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(imagejobinput.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(imagejobinput.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(imagejobinput.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(imagejobinput.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagejobinput.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagejobinput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagejobinput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imagejobinput.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobinput.JobTable,
			Columns: []string{imagejobinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagejobinput.JobTable,
			Columns: []string{imagejobinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageJobInput{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagejobinput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
