// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/imagejobinput"
	"github.com/Wei-Shaw/sub2api/ent/imagejobresult"
)

// ImageJobCreate is the builder for creating a ImageJob entity.
type ImageJobCreate struct {
	config
	mutation *ImageJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageJobCreate) SetCreatedAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableCreatedAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageJobCreate) SetUpdatedAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableUpdatedAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *ImageJobCreate) SetPublicID(v string) *ImageJobCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageJobCreate) SetUserID(v int64) *ImageJobCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ImageJobCreate) SetAPIKeyID(v int64) *ImageJobCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ImageJobCreate) SetGroupID(v int64) *ImageJobCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *ImageJobCreate) SetEndpoint(v string) *ImageJobCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *ImageJobCreate) SetOperation(v string) *ImageJobCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *ImageJobCreate) SetMode(v string) *ImageJobCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *ImageJobCreate) SetRequestedModel(v string) *ImageJobCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetMappedModel sets the "mapped_model" field.
func (_c *ImageJobCreate) SetMappedModel(v string) *ImageJobCreate {
	_c.mutation.SetMappedModel(v)
	return _c
}

// SetNillableMappedModel sets the "mapped_model" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableMappedModel(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetMappedModel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImageJobCreate) SetStatus(v string) *ImageJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetRequestedCount sets the "requested_count" field.
func (_c *ImageJobCreate) SetRequestedCount(v int) *ImageJobCreate {
	_c.mutation.SetRequestedCount(v)
	return _c
}

// SetCompletedCount sets the "completed_count" field.
func (_c *ImageJobCreate) SetCompletedCount(v int) *ImageJobCreate {
	_c.mutation.SetCompletedCount(v)
	return _c
}

// SetNillableCompletedCount sets the "completed_count" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableCompletedCount(v *int) *ImageJobCreate {
	if v != nil {
		_c.SetCompletedCount(*v)
	}
	return _c
}

// SetRequest sets the "request" field.
func (_c *ImageJobCreate) SetRequest(v json.RawMessage) *ImageJobCreate {
	_c.mutation.SetRequest(v)
	return _c
}

// SetRequestDigest sets the "request_digest" field.
func (_c *ImageJobCreate) SetRequestDigest(v string) *ImageJobCreate {
	_c.mutation.SetRequestDigest(v)
	return _c
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_c *ImageJobCreate) SetIdempotencyKeyHash(v string) *ImageJobCreate {
	_c.mutation.SetIdempotencyKeyHash(v)
	return _c
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableIdempotencyKeyHash(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetIdempotencyKeyHash(*v)
	}
	return _c
}

// SetReservedUsd sets the "reserved_usd" field.
func (_c *ImageJobCreate) SetReservedUsd(v float64) *ImageJobCreate {
	_c.mutation.SetReservedUsd(v)
	return _c
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableReservedUsd(v *float64) *ImageJobCreate {
	if v != nil {
		_c.SetReservedUsd(*v)
	}
	return _c
}

// SetReservationBillingType sets the "reservation_billing_type" field.
func (_c *ImageJobCreate) SetReservationBillingType(v int) *ImageJobCreate {
	_c.mutation.SetReservationBillingType(v)
	return _c
}

// SetNillableReservationBillingType sets the "reservation_billing_type" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableReservationBillingType(v *int) *ImageJobCreate {
	if v != nil {
		_c.SetReservationBillingType(*v)
	}
	return _c
}

// SetReservationSubscriptionID sets the "reservation_subscription_id" field.
func (_c *ImageJobCreate) SetReservationSubscriptionID(v int64) *ImageJobCreate {
	_c.mutation.SetReservationSubscriptionID(v)
	return _c
}

// SetNillableReservationSubscriptionID sets the "reservation_subscription_id" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableReservationSubscriptionID(v *int64) *ImageJobCreate {
	if v != nil {
		_c.SetReservationSubscriptionID(*v)
	}
	return _c
}

// SetReservationStatus sets the "reservation_status" field.
func (_c *ImageJobCreate) SetReservationStatus(v string) *ImageJobCreate {
	_c.mutation.SetReservationStatus(v)
	return _c
}

// SetNillableReservationStatus sets the "reservation_status" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableReservationStatus(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetReservationStatus(*v)
	}
	return _c
}

// SetUsage sets the "usage" field.
func (_c *ImageJobCreate) SetUsage(v json.RawMessage) *ImageJobCreate {
	_c.mutation.SetUsage(v)
	return _c
}

// SetSettlementStatus sets the "settlement_status" field.
func (_c *ImageJobCreate) SetSettlementStatus(v string) *ImageJobCreate {
	_c.mutation.SetSettlementStatus(v)
	return _c
}

// SetNillableSettlementStatus sets the "settlement_status" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableSettlementStatus(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetSettlementStatus(*v)
	}
	return _c
}

// SetAttemptID sets the "attempt_id" field.
func (_c *ImageJobCreate) SetAttemptID(v string) *ImageJobCreate {
	_c.mutation.SetAttemptID(v)
	return _c
}

// SetNillableAttemptID sets the "attempt_id" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableAttemptID(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetAttemptID(*v)
	}
	return _c
}

// SetWorkerID sets the "worker_id" field.
func (_c *ImageJobCreate) SetWorkerID(v string) *ImageJobCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableWorkerID(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetWorkerID(*v)
	}
	return _c
}

// SetExecutionPhase sets the "execution_phase" field.
func (_c *ImageJobCreate) SetExecutionPhase(v string) *ImageJobCreate {
	_c.mutation.SetExecutionPhase(v)
	return _c
}

// SetNillableExecutionPhase sets the "execution_phase" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableExecutionPhase(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetExecutionPhase(*v)
	}
	return _c
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_c *ImageJobCreate) SetHeartbeatAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetHeartbeatAt(v)
	return _c
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableHeartbeatAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetHeartbeatAt(*v)
	}
	return _c
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (_c *ImageJobCreate) SetCancelRequestedAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetCancelRequestedAt(v)
	return _c
}

// SetNillableCancelRequestedAt sets the "cancel_requested_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableCancelRequestedAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetCancelRequestedAt(*v)
	}
	return _c
}

// SetCanceledAt sets the "canceled_at" field.
func (_c *ImageJobCreate) SetCanceledAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetCanceledAt(v)
	return _c
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableCanceledAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetCanceledAt(*v)
	}
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *ImageJobCreate) SetErrorType(v string) *ImageJobCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableErrorType(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetErrorType(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *ImageJobCreate) SetErrorCode(v string) *ImageJobCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableErrorCode(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ImageJobCreate) SetErrorMessage(v string) *ImageJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableErrorMessage(v *string) *ImageJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetErrorRetryable sets the "error_retryable" field.
func (_c *ImageJobCreate) SetErrorRetryable(v bool) *ImageJobCreate {
	_c.mutation.SetErrorRetryable(v)
	return _c
}

// SetNillableErrorRetryable sets the "error_retryable" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableErrorRetryable(v *bool) *ImageJobCreate {
	if v != nil {
		_c.SetErrorRetryable(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ImageJobCreate) SetStartedAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableStartedAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ImageJobCreate) SetFinishedAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ImageJobCreate) SetNillableFinishedAt(v *time.Time) *ImageJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ImageJobCreate) SetExpiresAt(v time.Time) *ImageJobCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// AddInputIDs adds the "inputs" edge to the ImageJobInput entity by IDs.
func (_c *ImageJobCreate) AddInputIDs(ids ...int64) *ImageJobCreate {
	_c.mutation.AddInputIDs(ids...)
	return _c
}

// AddInputs adds the "inputs" edges to the ImageJobInput entity.
func (_c *ImageJobCreate) AddInputs(v ...*ImageJobInput) *ImageJobCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInputIDs(ids...)
}

// AddResultIDs adds the "results" edge to the ImageJobResult entity by IDs.
func (_c *ImageJobCreate) AddResultIDs(ids ...int64) *ImageJobCreate {
	_c.mutation.AddResultIDs(ids...)
	return _c
}

// AddResults adds the "results" edges to the ImageJobResult entity.
func (_c *ImageJobCreate) AddResults(v ...*ImageJobResult) *ImageJobCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResultIDs(ids...)
}

// Mutation returns the ImageJobMutation object of the builder.
func (_c *ImageJobCreate) Mutation() *ImageJobMutation {
	return _c.mutation
}

// Save creates the ImageJob in the database.
func (_c *ImageJobCreate) Save(ctx context.Context) (*ImageJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageJobCreate) SaveX(ctx context.Context) *ImageJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagejob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imagejob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MappedModel(); !ok {
		v := imagejob.DefaultMappedModel
		_c.mutation.SetMappedModel(v)
	}
	if _, ok := _c.mutation.CompletedCount(); !ok {
		v := imagejob.DefaultCompletedCount
		_c.mutation.SetCompletedCount(v)
	}
	if _, ok := _c.mutation.ReservedUsd(); !ok {
		v := imagejob.DefaultReservedUsd
		_c.mutation.SetReservedUsd(v)
	}
	if _, ok := _c.mutation.ReservationBillingType(); !ok {
		v := imagejob.DefaultReservationBillingType
		_c.mutation.SetReservationBillingType(v)
	}
	if _, ok := _c.mutation.ReservationStatus(); !ok {
		v := imagejob.DefaultReservationStatus
		_c.mutation.SetReservationStatus(v)
	}
	if _, ok := _c.mutation.SettlementStatus(); !ok {
		v := imagejob.DefaultSettlementStatus
		_c.mutation.SetSettlementStatus(v)
	}
	if _, ok := _c.mutation.ExecutionPhase(); !ok {
		v := imagejob.DefaultExecutionPhase
		_c.mutation.SetExecutionPhase(v)
	}
	if _, ok := _c.mutation.ErrorRetryable(); !ok {
		v := imagejob.DefaultErrorRetryable
		_c.mutation.SetErrorRetryable(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageJob.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "ImageJob.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := imagejob.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "ImageJob.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageJob.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ImageJob.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ImageJob.group_id"`)}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "ImageJob.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := imagejob.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ImageJob.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "ImageJob.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := imagejob.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "ImageJob.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "ImageJob.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := imagejob.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageJob.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "ImageJob.requested_model"`)}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := imagejob.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "ImageJob.requested_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MappedModel(); !ok {
		return &ValidationError{Name: "mapped_model", err: errors.New(`ent: missing required field "ImageJob.mapped_model"`)}
	}
	if v, ok := _c.mutation.MappedModel(); ok {
		if err := imagejob.MappedModelValidator(v); err != nil {
			return &ValidationError{Name: "mapped_model", err: fmt.Errorf(`ent: validator failed for field "ImageJob.mapped_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImageJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imagejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedCount(); !ok {
		return &ValidationError{Name: "requested_count", err: errors.New(`ent: missing required field "ImageJob.requested_count"`)}
	}
	if _, ok := _c.mutation.CompletedCount(); !ok {
		return &ValidationError{Name: "completed_count", err: errors.New(`ent: missing required field "ImageJob.completed_count"`)}
	}
	if _, ok := _c.mutation.Request(); !ok {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required field "ImageJob.request"`)}
	}
	if _, ok := _c.mutation.RequestDigest(); !ok {
		return &ValidationError{Name: "request_digest", err: errors.New(`ent: missing required field "ImageJob.request_digest"`)}
	}
	if v, ok := _c.mutation.RequestDigest(); ok {
		if err := imagejob.RequestDigestValidator(v); err != nil {
			return &ValidationError{Name: "request_digest", err: fmt.Errorf(`ent: validator failed for field "ImageJob.request_digest": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKeyHash(); ok {
		if err := imagejob.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "ImageJob.idempotency_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReservedUsd(); !ok {
		return &ValidationError{Name: "reserved_usd", err: errors.New(`ent: missing required field "ImageJob.reserved_usd"`)}
	}
	if _, ok := _c.mutation.ReservationBillingType(); !ok {
		return &ValidationError{Name: "reservation_billing_type", err: errors.New(`ent: missing required field "ImageJob.reservation_billing_type"`)}
	}
	if _, ok := _c.mutation.ReservationStatus(); !ok {
		return &ValidationError{Name: "reservation_status", err: errors.New(`ent: missing required field "ImageJob.reservation_status"`)}
	}
	if v, ok := _c.mutation.ReservationStatus(); ok {
		if err := imagejob.ReservationStatusValidator(v); err != nil {
			return &ValidationError{Name: "reservation_status", err: fmt.Errorf(`ent: validator failed for field "ImageJob.reservation_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettlementStatus(); !ok {
		return &ValidationError{Name: "settlement_status", err: errors.New(`ent: missing required field "ImageJob.settlement_status"`)}
	}
	if v, ok := _c.mutation.SettlementStatus(); ok {
		if err := imagejob.SettlementStatusValidator(v); err != nil {
			return &ValidationError{Name: "settlement_status", err: fmt.Errorf(`ent: validator failed for field "ImageJob.settlement_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AttemptID(); ok {
		if err := imagejob.AttemptIDValidator(v); err != nil {
			return &ValidationError{Name: "attempt_id", err: fmt.Errorf(`ent: validator failed for field "ImageJob.attempt_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WorkerID(); ok {
		if err := imagejob.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "ImageJob.worker_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionPhase(); !ok {
		return &ValidationError{Name: "execution_phase", err: errors.New(`ent: missing required field "ImageJob.execution_phase"`)}
	}
	if v, ok := _c.mutation.ExecutionPhase(); ok {
		if err := imagejob.ExecutionPhaseValidator(v); err != nil {
			return &ValidationError{Name: "execution_phase", err: fmt.Errorf(`ent: validator failed for field "ImageJob.execution_phase": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorType(); ok {
		if err := imagejob.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "ImageJob.error_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := imagejob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageJob.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorRetryable(); !ok {
		return &ValidationError{Name: "error_retryable", err: errors.New(`ent: missing required field "ImageJob.error_retryable"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ImageJob.expires_at"`)}
	}
	return nil
}

func (_c *ImageJobCreate) sqlSave(ctx context.Context) (*ImageJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageJobCreate) createSpec() (*ImageJob, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagejob.Table, sqlgraph.NewFieldSpec(imagejob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagejob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imagejob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(imagejob.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imagejob.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(imagejob.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(imagejob.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(imagejob.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(imagejob.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(imagejob.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(imagejob.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.MappedModel(); ok {
		_spec.SetField(imagejob.FieldMappedModel, field.TypeString, value)
		_node.MappedModel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imagejob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestedCount(); ok {
		_spec.SetField(imagejob.FieldRequestedCount, field.TypeInt, value)
		_node.RequestedCount = value
	}
	if value, ok := _c.mutation.CompletedCount(); ok {
		_spec.SetField(imagejob.FieldCompletedCount, field.TypeInt, value)
		_node.CompletedCount = value
	}
	if value, ok := _c.mutation.Request(); ok {
		_spec.SetField(imagejob.FieldRequest, field.TypeJSON, value)
		_node.Request = value
	}
	if value, ok := _c.mutation.RequestDigest(); ok {
		_spec.SetField(imagejob.FieldRequestDigest, field.TypeString, value)
		_node.RequestDigest = value
	}
	if value, ok := _c.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(imagejob.FieldIdempotencyKeyHash, field.TypeString, value)
		_node.IdempotencyKeyHash = &value
	}
	if value, ok := _c.mutation.ReservedUsd(); ok {
		_spec.SetField(imagejob.FieldReservedUsd, field.TypeFloat64, value)
		_node.ReservedUsd = value
	}
	if value, ok := _c.mutation.ReservationBillingType(); ok {
		_spec.SetField(imagejob.FieldReservationBillingType, field.TypeInt, value)
		_node.ReservationBillingType = value
	}
	if value, ok := _c.mutation.ReservationSubscriptionID(); ok {
		_spec.SetField(imagejob.FieldReservationSubscriptionID, field.TypeInt64, value)
		_node.ReservationSubscriptionID = &value
	}
	if value, ok := _c.mutation.ReservationStatus(); ok {
		_spec.SetField(imagejob.FieldReservationStatus, field.TypeString, value)
		_node.ReservationStatus = value
	}
	if value, ok := _c.mutation.Usage(); ok {
		_spec.SetField(imagejob.FieldUsage, field.TypeJSON, value)
		_node.Usage = value
	}
	if value, ok := _c.mutation.SettlementStatus(); ok {
		_spec.SetField(imagejob.FieldSettlementStatus, field.TypeString, value)
		_node.SettlementStatus = value
	}
	if value, ok := _c.mutation.AttemptID(); ok {
		_spec.SetField(imagejob.FieldAttemptID, field.TypeString, value)
		_node.AttemptID = &value
	}
	if value, ok := _c.mutation.WorkerID(); ok {
		_spec.SetField(imagejob.FieldWorkerID, field.TypeString, value)
		_node.WorkerID = &value
	}
	if value, ok := _c.mutation.ExecutionPhase(); ok {
		_spec.SetField(imagejob.FieldExecutionPhase, field.TypeString, value)
		_node.ExecutionPhase = value
	}
	if value, ok := _c.mutation.HeartbeatAt(); ok {
		_spec.SetField(imagejob.FieldHeartbeatAt, field.TypeTime, value)
		_node.HeartbeatAt = &value
	}
	if value, ok := _c.mutation.CancelRequestedAt(); ok {
		_spec.SetField(imagejob.FieldCancelRequestedAt, field.TypeTime, value)
		_node.CancelRequestedAt = &value
	}
	if value, ok := _c.mutation.CanceledAt(); ok {
		_spec.SetField(imagejob.FieldCanceledAt, field.TypeTime, value)
		_node.CanceledAt = &value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(imagejob.FieldErrorType, field.TypeString, value)
		_node.ErrorType = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(imagejob.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(imagejob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.ErrorRetryable(); ok {
		_spec.SetField(imagejob.FieldErrorRetryable, field.TypeBool, value)
		_node.ErrorRetryable = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(imagejob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(imagejob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(imagejob.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.InputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagejob.InputsTable,
			Columns: []string{imagejob.InputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejobinput.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagejob.ResultsTable,
			Columns: []string{imagejob.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagejobresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJob.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobCreate) OnConflict(opts ...sql.ConflictOption) *ImageJobUpsertOne {
	_c.conflict = opts
	return &ImageJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobCreate) OnConflictColumns(columns ...string) *ImageJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobUpsertOne{
		create: _c,
	}
}

type (
	// ImageJobUpsertOne is the builder for "upsert"-ing
	//  one ImageJob node.
	ImageJobUpsertOne struct {
		create *ImageJobCreate
	}

	// ImageJobUpsert is the "OnConflict" setter.
	ImageJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobUpsert) SetUpdatedAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateUpdatedAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldUpdatedAt)
	return u
}

// SetPublicID sets the "public_id" field.
func (u *ImageJobUpsert) SetPublicID(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldPublicID, v)
	return u
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdatePublicID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldPublicID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageJobUpsert) SetUserID(v int64) *ImageJobUpsert {
	u.Set(imagejob.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateUserID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ImageJobUpsert) AddUserID(v int64) *ImageJobUpsert {
	u.Add(imagejob.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageJobUpsert) SetAPIKeyID(v int64) *ImageJobUpsert {
	u.Set(imagejob.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateAPIKeyID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageJobUpsert) AddAPIKeyID(v int64) *ImageJobUpsert {
	u.Add(imagejob.FieldAPIKeyID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ImageJobUpsert) SetGroupID(v int64) *ImageJobUpsert {
	u.Set(imagejob.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateGroupID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageJobUpsert) AddGroupID(v int64) *ImageJobUpsert {
	u.Add(imagejob.FieldGroupID, v)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageJobUpsert) SetEndpoint(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateEndpoint() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldEndpoint)
	return u
}

// SetOperation sets the "operation" field.
func (u *ImageJobUpsert) SetOperation(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateOperation() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldOperation)
	return u
}

// SetMode sets the "mode" field.
func (u *ImageJobUpsert) SetMode(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateMode() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldMode)
	return u
}

// SetRequestedModel sets the "requested_model" field.
func (u *ImageJobUpsert) SetRequestedModel(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldRequestedModel, v)
	return u
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateRequestedModel() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldRequestedModel)
	return u
}

// SetMappedModel sets the "mapped_model" field.
func (u *ImageJobUpsert) SetMappedModel(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldMappedModel, v)
	return u
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateMappedModel() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldMappedModel)
	return u
}

// SetStatus sets the "status" field.
func (u *ImageJobUpsert) SetStatus(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateStatus() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldStatus)
	return u
}

// SetRequestedCount sets the "requested_count" field.
func (u *ImageJobUpsert) SetRequestedCount(v int) *ImageJobUpsert {
	u.Set(imagejob.FieldRequestedCount, v)
	return u
}

// UpdateRequestedCount sets the "requested_count" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateRequestedCount() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldRequestedCount)
	return u
}

// AddRequestedCount adds v to the "requested_count" field.
func (u *ImageJobUpsert) AddRequestedCount(v int) *ImageJobUpsert {
	u.Add(imagejob.FieldRequestedCount, v)
	return u
}

// SetCompletedCount sets the "completed_count" field.
func (u *ImageJobUpsert) SetCompletedCount(v int) *ImageJobUpsert {
	u.Set(imagejob.FieldCompletedCount, v)
	return u
}

// UpdateCompletedCount sets the "completed_count" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateCompletedCount() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldCompletedCount)
	return u
}

// AddCompletedCount adds v to the "completed_count" field.
func (u *ImageJobUpsert) AddCompletedCount(v int) *ImageJobUpsert {
	u.Add(imagejob.FieldCompletedCount, v)
	return u
}

// SetRequest sets the "request" field.
func (u *ImageJobUpsert) SetRequest(v json.RawMessage) *ImageJobUpsert {
	u.Set(imagejob.FieldRequest, v)
	return u
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateRequest() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldRequest)
	return u
}

// SetRequestDigest sets the "request_digest" field.
func (u *ImageJobUpsert) SetRequestDigest(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldRequestDigest, v)
	return u
}

// UpdateRequestDigest sets the "request_digest" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateRequestDigest() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldRequestDigest)
	return u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *ImageJobUpsert) SetIdempotencyKeyHash(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldIdempotencyKeyHash, v)
	return u
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateIdempotencyKeyHash() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldIdempotencyKeyHash)
	return u
}

// ClearIdempotencyKeyHash clears the value of the "idempotency_key_hash" field.
func (u *ImageJobUpsert) ClearIdempotencyKeyHash() *ImageJobUpsert {
	u.SetNull(imagejob.FieldIdempotencyKeyHash)
	return u
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *ImageJobUpsert) SetReservedUsd(v float64) *ImageJobUpsert {
	u.Set(imagejob.FieldReservedUsd, v)
	return u
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateReservedUsd() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldReservedUsd)
	return u
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *ImageJobUpsert) AddReservedUsd(v float64) *ImageJobUpsert {
	u.Add(imagejob.FieldReservedUsd, v)
	return u
}

// SetReservationBillingType sets the "reservation_billing_type" field.
func (u *ImageJobUpsert) SetReservationBillingType(v int) *ImageJobUpsert {
	u.Set(imagejob.FieldReservationBillingType, v)
	return u
}

// UpdateReservationBillingType sets the "reservation_billing_type" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateReservationBillingType() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldReservationBillingType)
	return u
}

// AddReservationBillingType adds v to the "reservation_billing_type" field.
func (u *ImageJobUpsert) AddReservationBillingType(v int) *ImageJobUpsert {
	u.Add(imagejob.FieldReservationBillingType, v)
	return u
}

// SetReservationSubscriptionID sets the "reservation_subscription_id" field.
func (u *ImageJobUpsert) SetReservationSubscriptionID(v int64) *ImageJobUpsert {
	u.Set(imagejob.FieldReservationSubscriptionID, v)
	return u
}

// UpdateReservationSubscriptionID sets the "reservation_subscription_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateReservationSubscriptionID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldReservationSubscriptionID)
	return u
}

// AddReservationSubscriptionID adds v to the "reservation_subscription_id" field.
func (u *ImageJobUpsert) AddReservationSubscriptionID(v int64) *ImageJobUpsert {
	u.Add(imagejob.FieldReservationSubscriptionID, v)
	return u
}

// ClearReservationSubscriptionID clears the value of the "reservation_subscription_id" field.
func (u *ImageJobUpsert) ClearReservationSubscriptionID() *ImageJobUpsert {
	u.SetNull(imagejob.FieldReservationSubscriptionID)
	return u
}

// SetReservationStatus sets the "reservation_status" field.
func (u *ImageJobUpsert) SetReservationStatus(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldReservationStatus, v)
	return u
}

// UpdateReservationStatus sets the "reservation_status" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateReservationStatus() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldReservationStatus)
	return u
}

// SetUsage sets the "usage" field.
func (u *ImageJobUpsert) SetUsage(v json.RawMessage) *ImageJobUpsert {
	u.Set(imagejob.FieldUsage, v)
	return u
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateUsage() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldUsage)
	return u
}

// ClearUsage clears the value of the "usage" field.
func (u *ImageJobUpsert) ClearUsage() *ImageJobUpsert {
	u.SetNull(imagejob.FieldUsage)
	return u
}

// SetSettlementStatus sets the "settlement_status" field.
func (u *ImageJobUpsert) SetSettlementStatus(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldSettlementStatus, v)
	return u
}

// UpdateSettlementStatus sets the "settlement_status" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateSettlementStatus() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldSettlementStatus)
	return u
}

// SetAttemptID sets the "attempt_id" field.
func (u *ImageJobUpsert) SetAttemptID(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldAttemptID, v)
	return u
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateAttemptID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldAttemptID)
	return u
}

// ClearAttemptID clears the value of the "attempt_id" field.
func (u *ImageJobUpsert) ClearAttemptID() *ImageJobUpsert {
	u.SetNull(imagejob.FieldAttemptID)
	return u
}

// SetWorkerID sets the "worker_id" field.
func (u *ImageJobUpsert) SetWorkerID(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldWorkerID, v)
	return u
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateWorkerID() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldWorkerID)
	return u
}

// ClearWorkerID clears the value of the "worker_id" field.
func (u *ImageJobUpsert) ClearWorkerID() *ImageJobUpsert {
	u.SetNull(imagejob.FieldWorkerID)
	return u
}

// SetExecutionPhase sets the "execution_phase" field.
func (u *ImageJobUpsert) SetExecutionPhase(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldExecutionPhase, v)
	return u
}

// UpdateExecutionPhase sets the "execution_phase" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateExecutionPhase() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldExecutionPhase)
	return u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *ImageJobUpsert) SetHeartbeatAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldHeartbeatAt, v)
	return u
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateHeartbeatAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldHeartbeatAt)
	return u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *ImageJobUpsert) ClearHeartbeatAt() *ImageJobUpsert {
	u.SetNull(imagejob.FieldHeartbeatAt)
	return u
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *ImageJobUpsert) SetCancelRequestedAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldCancelRequestedAt, v)
	return u
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateCancelRequestedAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldCancelRequestedAt)
	return u
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *ImageJobUpsert) ClearCancelRequestedAt() *ImageJobUpsert {
	u.SetNull(imagejob.FieldCancelRequestedAt)
	return u
}

// SetCanceledAt sets the "canceled_at" field.
func (u *ImageJobUpsert) SetCanceledAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldCanceledAt, v)
	return u
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateCanceledAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldCanceledAt)
	return u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *ImageJobUpsert) ClearCanceledAt() *ImageJobUpsert {
	u.SetNull(imagejob.FieldCanceledAt)
	return u
}

// SetErrorType sets the "error_type" field.
func (u *ImageJobUpsert) SetErrorType(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldErrorType, v)
	return u
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateErrorType() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldErrorType)
	return u
}

// ClearErrorType clears the value of the "error_type" field.
func (u *ImageJobUpsert) ClearErrorType() *ImageJobUpsert {
	u.SetNull(imagejob.FieldErrorType)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *ImageJobUpsert) SetErrorCode(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateErrorCode() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageJobUpsert) ClearErrorCode() *ImageJobUpsert {
	u.SetNull(imagejob.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageJobUpsert) SetErrorMessage(v string) *ImageJobUpsert {
	u.Set(imagejob.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateErrorMessage() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageJobUpsert) ClearErrorMessage() *ImageJobUpsert {
	u.SetNull(imagejob.FieldErrorMessage)
	return u
}

// SetErrorRetryable sets the "error_retryable" field.
func (u *ImageJobUpsert) SetErrorRetryable(v bool) *ImageJobUpsert {
	u.Set(imagejob.FieldErrorRetryable, v)
	return u
}

// UpdateErrorRetryable sets the "error_retryable" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateErrorRetryable() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldErrorRetryable)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ImageJobUpsert) SetStartedAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateStartedAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageJobUpsert) ClearStartedAt() *ImageJobUpsert {
	u.SetNull(imagejob.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *ImageJobUpsert) SetFinishedAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateFinishedAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ImageJobUpsert) ClearFinishedAt() *ImageJobUpsert {
	u.SetNull(imagejob.FieldFinishedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImageJobUpsert) SetExpiresAt(v time.Time) *ImageJobUpsert {
	u.Set(imagejob.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImageJobUpsert) UpdateExpiresAt() *ImageJobUpsert {
	u.SetExcluded(imagejob.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobUpsertOne) UpdateNewValues() *ImageJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagejob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageJobUpsertOne) Ignore() *ImageJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobUpsertOne) DoNothing() *ImageJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobCreate.OnConflict
// documentation for more info.
func (u *ImageJobUpsertOne) Update(set func(*ImageJobUpsert)) *ImageJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobUpsertOne) SetUpdatedAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateUpdatedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *ImageJobUpsertOne) SetPublicID(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdatePublicID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageJobUpsertOne) SetUserID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageJobUpsertOne) AddUserID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateUserID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageJobUpsertOne) SetAPIKeyID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageJobUpsertOne) AddAPIKeyID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateAPIKeyID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ImageJobUpsertOne) SetGroupID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageJobUpsertOne) AddGroupID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateGroupID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateGroupID()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageJobUpsertOne) SetEndpoint(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateEndpoint() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateEndpoint()
	})
}

// SetOperation sets the "operation" field.
func (u *ImageJobUpsertOne) SetOperation(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateOperation() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateOperation()
	})
}

// SetMode sets the "mode" field.
func (u *ImageJobUpsertOne) SetMode(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateMode() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateMode()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *ImageJobUpsertOne) SetRequestedModel(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateRequestedModel() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *ImageJobUpsertOne) SetMappedModel(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateMappedModel() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateMappedModel()
	})
}

// SetStatus sets the "status" field.
func (u *ImageJobUpsertOne) SetStatus(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateStatus() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedCount sets the "requested_count" field.
func (u *ImageJobUpsertOne) SetRequestedCount(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestedCount(v)
	})
}

// AddRequestedCount adds v to the "requested_count" field.
func (u *ImageJobUpsertOne) AddRequestedCount(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddRequestedCount(v)
	})
}

// UpdateRequestedCount sets the "requested_count" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateRequestedCount() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestedCount()
	})
}

// SetCompletedCount sets the "completed_count" field.
func (u *ImageJobUpsertOne) SetCompletedCount(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCompletedCount(v)
	})
}

// AddCompletedCount adds v to the "completed_count" field.
func (u *ImageJobUpsertOne) AddCompletedCount(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddCompletedCount(v)
	})
}

// UpdateCompletedCount sets the "completed_count" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateCompletedCount() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCompletedCount()
	})
}

// SetRequest sets the "request" field.
func (u *ImageJobUpsertOne) SetRequest(v json.RawMessage) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequest(v)
	})
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateRequest() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequest()
	})
}

// SetRequestDigest sets the "request_digest" field.
func (u *ImageJobUpsertOne) SetRequestDigest(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestDigest(v)
	})
}

// UpdateRequestDigest sets the "request_digest" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateRequestDigest() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestDigest()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *ImageJobUpsertOne) SetIdempotencyKeyHash(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateIdempotencyKeyHash() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// ClearIdempotencyKeyHash clears the value of the "idempotency_key_hash" field.
func (u *ImageJobUpsertOne) ClearIdempotencyKeyHash() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearIdempotencyKeyHash()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *ImageJobUpsertOne) SetReservedUsd(v float64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *ImageJobUpsertOne) AddReservedUsd(v float64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateReservedUsd() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetReservationBillingType sets the "reservation_billing_type" field.
func (u *ImageJobUpsertOne) SetReservationBillingType(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationBillingType(v)
	})
}

// AddReservationBillingType adds v to the "reservation_billing_type" field.
func (u *ImageJobUpsertOne) AddReservationBillingType(v int) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservationBillingType(v)
	})
}

// UpdateReservationBillingType sets the "reservation_billing_type" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateReservationBillingType() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationBillingType()
	})
}

// SetReservationSubscriptionID sets the "reservation_subscription_id" field.
func (u *ImageJobUpsertOne) SetReservationSubscriptionID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationSubscriptionID(v)
	})
}

// AddReservationSubscriptionID adds v to the "reservation_subscription_id" field.
func (u *ImageJobUpsertOne) AddReservationSubscriptionID(v int64) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservationSubscriptionID(v)
	})
}

// UpdateReservationSubscriptionID sets the "reservation_subscription_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateReservationSubscriptionID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationSubscriptionID()
	})
}

// ClearReservationSubscriptionID clears the value of the "reservation_subscription_id" field.
func (u *ImageJobUpsertOne) ClearReservationSubscriptionID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearReservationSubscriptionID()
	})
}

// SetReservationStatus sets the "reservation_status" field.
func (u *ImageJobUpsertOne) SetReservationStatus(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationStatus(v)
	})
}

// UpdateReservationStatus sets the "reservation_status" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateReservationStatus() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationStatus()
	})
}

// SetUsage sets the "usage" field.
func (u *ImageJobUpsertOne) SetUsage(v json.RawMessage) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateUsage() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *ImageJobUpsertOne) ClearUsage() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearUsage()
	})
}

// SetSettlementStatus sets the "settlement_status" field.
func (u *ImageJobUpsertOne) SetSettlementStatus(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetSettlementStatus(v)
	})
}

// UpdateSettlementStatus sets the "settlement_status" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateSettlementStatus() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateSettlementStatus()
	})
}

// SetAttemptID sets the "attempt_id" field.
func (u *ImageJobUpsertOne) SetAttemptID(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetAttemptID(v)
	})
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateAttemptID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateAttemptID()
	})
}

// ClearAttemptID clears the value of the "attempt_id" field.
func (u *ImageJobUpsertOne) ClearAttemptID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearAttemptID()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *ImageJobUpsertOne) SetWorkerID(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateWorkerID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateWorkerID()
	})
}

// ClearWorkerID clears the value of the "worker_id" field.
func (u *ImageJobUpsertOne) ClearWorkerID() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearWorkerID()
	})
}

// SetExecutionPhase sets the "execution_phase" field.
func (u *ImageJobUpsertOne) SetExecutionPhase(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetExecutionPhase(v)
	})
}

// UpdateExecutionPhase sets the "execution_phase" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateExecutionPhase() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateExecutionPhase()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *ImageJobUpsertOne) SetHeartbeatAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateHeartbeatAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *ImageJobUpsertOne) ClearHeartbeatAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearHeartbeatAt()
	})
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *ImageJobUpsertOne) SetCancelRequestedAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCancelRequestedAt(v)
	})
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateCancelRequestedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCancelRequestedAt()
	})
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *ImageJobUpsertOne) ClearCancelRequestedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearCancelRequestedAt()
	})
}

// SetCanceledAt sets the "canceled_at" field.
func (u *ImageJobUpsertOne) SetCanceledAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCanceledAt(v)
	})
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateCanceledAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCanceledAt()
	})
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *ImageJobUpsertOne) ClearCanceledAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearCanceledAt()
	})
}

// SetErrorType sets the "error_type" field.
func (u *ImageJobUpsertOne) SetErrorType(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateErrorType() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorType()
	})
}

// ClearErrorType clears the value of the "error_type" field.
func (u *ImageJobUpsertOne) ClearErrorType() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorType()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageJobUpsertOne) SetErrorCode(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateErrorCode() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageJobUpsertOne) ClearErrorCode() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageJobUpsertOne) SetErrorMessage(v string) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateErrorMessage() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageJobUpsertOne) ClearErrorMessage() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorRetryable sets the "error_retryable" field.
func (u *ImageJobUpsertOne) SetErrorRetryable(v bool) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorRetryable(v)
	})
}

// UpdateErrorRetryable sets the "error_retryable" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateErrorRetryable() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorRetryable()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ImageJobUpsertOne) SetStartedAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateStartedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageJobUpsertOne) ClearStartedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *ImageJobUpsertOne) SetFinishedAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateFinishedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ImageJobUpsertOne) ClearFinishedAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearFinishedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImageJobUpsertOne) SetExpiresAt(v time.Time) *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImageJobUpsertOne) UpdateExpiresAt() *ImageJobUpsertOne {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ImageJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageJobCreateBulk is the builder for creating many ImageJob entities in bulk.
type ImageJobCreateBulk struct {
	config
	err      error
	builders []*ImageJobCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageJob entities in the database.
func (_c *ImageJobCreateBulk) Save(ctx context.Context) ([]*ImageJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageJobCreateBulk) SaveX(ctx context.Context) []*ImageJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageJobUpsertBulk {
	_c.conflict = opts
	return &ImageJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageJobCreateBulk) OnConflictColumns(columns ...string) *ImageJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageJobUpsertBulk{
		create: _c,
	}
}

// ImageJobUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageJob nodes.
type ImageJobUpsertBulk struct {
	create *ImageJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageJobUpsertBulk) UpdateNewValues() *ImageJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagejob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageJobUpsertBulk) Ignore() *ImageJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageJobUpsertBulk) DoNothing() *ImageJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageJobCreateBulk.OnConflict
// documentation for more info.
func (u *ImageJobUpsertBulk) Update(set func(*ImageJobUpsert)) *ImageJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageJobUpsertBulk) SetUpdatedAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateUpdatedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *ImageJobUpsertBulk) SetPublicID(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdatePublicID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageJobUpsertBulk) SetUserID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageJobUpsertBulk) AddUserID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateUserID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageJobUpsertBulk) SetAPIKeyID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageJobUpsertBulk) AddAPIKeyID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateAPIKeyID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ImageJobUpsertBulk) SetGroupID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageJobUpsertBulk) AddGroupID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateGroupID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateGroupID()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageJobUpsertBulk) SetEndpoint(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateEndpoint() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateEndpoint()
	})
}

// SetOperation sets the "operation" field.
func (u *ImageJobUpsertBulk) SetOperation(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateOperation() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateOperation()
	})
}

// SetMode sets the "mode" field.
func (u *ImageJobUpsertBulk) SetMode(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateMode() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateMode()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *ImageJobUpsertBulk) SetRequestedModel(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateRequestedModel() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *ImageJobUpsertBulk) SetMappedModel(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateMappedModel() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateMappedModel()
	})
}

// SetStatus sets the "status" field.
func (u *ImageJobUpsertBulk) SetStatus(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateStatus() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedCount sets the "requested_count" field.
func (u *ImageJobUpsertBulk) SetRequestedCount(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestedCount(v)
	})
}

// AddRequestedCount adds v to the "requested_count" field.
func (u *ImageJobUpsertBulk) AddRequestedCount(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddRequestedCount(v)
	})
}

// UpdateRequestedCount sets the "requested_count" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateRequestedCount() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestedCount()
	})
}

// SetCompletedCount sets the "completed_count" field.
func (u *ImageJobUpsertBulk) SetCompletedCount(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCompletedCount(v)
	})
}

// AddCompletedCount adds v to the "completed_count" field.
func (u *ImageJobUpsertBulk) AddCompletedCount(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddCompletedCount(v)
	})
}

// UpdateCompletedCount sets the "completed_count" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateCompletedCount() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCompletedCount()
	})
}

// SetRequest sets the "request" field.
func (u *ImageJobUpsertBulk) SetRequest(v json.RawMessage) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequest(v)
	})
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateRequest() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequest()
	})
}

// SetRequestDigest sets the "request_digest" field.
func (u *ImageJobUpsertBulk) SetRequestDigest(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetRequestDigest(v)
	})
}

// UpdateRequestDigest sets the "request_digest" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateRequestDigest() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateRequestDigest()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *ImageJobUpsertBulk) SetIdempotencyKeyHash(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateIdempotencyKeyHash() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// ClearIdempotencyKeyHash clears the value of the "idempotency_key_hash" field.
func (u *ImageJobUpsertBulk) ClearIdempotencyKeyHash() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearIdempotencyKeyHash()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *ImageJobUpsertBulk) SetReservedUsd(v float64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *ImageJobUpsertBulk) AddReservedUsd(v float64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateReservedUsd() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetReservationBillingType sets the "reservation_billing_type" field.
func (u *ImageJobUpsertBulk) SetReservationBillingType(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationBillingType(v)
	})
}

// AddReservationBillingType adds v to the "reservation_billing_type" field.
func (u *ImageJobUpsertBulk) AddReservationBillingType(v int) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservationBillingType(v)
	})
}

// UpdateReservationBillingType sets the "reservation_billing_type" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateReservationBillingType() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationBillingType()
	})
}

// SetReservationSubscriptionID sets the "reservation_subscription_id" field.
func (u *ImageJobUpsertBulk) SetReservationSubscriptionID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationSubscriptionID(v)
	})
}

// AddReservationSubscriptionID adds v to the "reservation_subscription_id" field.
func (u *ImageJobUpsertBulk) AddReservationSubscriptionID(v int64) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.AddReservationSubscriptionID(v)
	})
}

// UpdateReservationSubscriptionID sets the "reservation_subscription_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateReservationSubscriptionID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationSubscriptionID()
	})
}

// ClearReservationSubscriptionID clears the value of the "reservation_subscription_id" field.
func (u *ImageJobUpsertBulk) ClearReservationSubscriptionID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearReservationSubscriptionID()
	})
}

// SetReservationStatus sets the "reservation_status" field.
func (u *ImageJobUpsertBulk) SetReservationStatus(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetReservationStatus(v)
	})
}

// UpdateReservationStatus sets the "reservation_status" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateReservationStatus() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateReservationStatus()
	})
}

// SetUsage sets the "usage" field.
func (u *ImageJobUpsertBulk) SetUsage(v json.RawMessage) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateUsage() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *ImageJobUpsertBulk) ClearUsage() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearUsage()
	})
}

// SetSettlementStatus sets the "settlement_status" field.
func (u *ImageJobUpsertBulk) SetSettlementStatus(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetSettlementStatus(v)
	})
}

// UpdateSettlementStatus sets the "settlement_status" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateSettlementStatus() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateSettlementStatus()
	})
}

// SetAttemptID sets the "attempt_id" field.
func (u *ImageJobUpsertBulk) SetAttemptID(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetAttemptID(v)
	})
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateAttemptID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateAttemptID()
	})
}

// ClearAttemptID clears the value of the "attempt_id" field.
func (u *ImageJobUpsertBulk) ClearAttemptID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearAttemptID()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *ImageJobUpsertBulk) SetWorkerID(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateWorkerID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateWorkerID()
	})
}

// ClearWorkerID clears the value of the "worker_id" field.
func (u *ImageJobUpsertBulk) ClearWorkerID() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearWorkerID()
	})
}

// SetExecutionPhase sets the "execution_phase" field.
func (u *ImageJobUpsertBulk) SetExecutionPhase(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetExecutionPhase(v)
	})
}

// UpdateExecutionPhase sets the "execution_phase" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateExecutionPhase() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateExecutionPhase()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *ImageJobUpsertBulk) SetHeartbeatAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateHeartbeatAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *ImageJobUpsertBulk) ClearHeartbeatAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearHeartbeatAt()
	})
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *ImageJobUpsertBulk) SetCancelRequestedAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCancelRequestedAt(v)
	})
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateCancelRequestedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCancelRequestedAt()
	})
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *ImageJobUpsertBulk) ClearCancelRequestedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearCancelRequestedAt()
	})
}

// SetCanceledAt sets the "canceled_at" field.
func (u *ImageJobUpsertBulk) SetCanceledAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetCanceledAt(v)
	})
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateCanceledAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateCanceledAt()
	})
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *ImageJobUpsertBulk) ClearCanceledAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearCanceledAt()
	})
}

// SetErrorType sets the "error_type" field.
func (u *ImageJobUpsertBulk) SetErrorType(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateErrorType() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorType()
	})
}

// ClearErrorType clears the value of the "error_type" field.
func (u *ImageJobUpsertBulk) ClearErrorType() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorType()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageJobUpsertBulk) SetErrorCode(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateErrorCode() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageJobUpsertBulk) ClearErrorCode() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageJobUpsertBulk) SetErrorMessage(v string) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateErrorMessage() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageJobUpsertBulk) ClearErrorMessage() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorRetryable sets the "error_retryable" field.
func (u *ImageJobUpsertBulk) SetErrorRetryable(v bool) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetErrorRetryable(v)
	})
}

// UpdateErrorRetryable sets the "error_retryable" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateErrorRetryable() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateErrorRetryable()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ImageJobUpsertBulk) SetStartedAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateStartedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageJobUpsertBulk) ClearStartedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *ImageJobUpsertBulk) SetFinishedAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateFinishedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ImageJobUpsertBulk) ClearFinishedAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.ClearFinishedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImageJobUpsertBulk) SetExpiresAt(v time.Time) *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImageJobUpsertBulk) UpdateExpiresAt() *ImageJobUpsertBulk {
	return u.Update(func(s *ImageJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ImageJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
