// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/imagejob"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageJob is the model entity for the ImageJob schema.
type ImageJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// MappedModel holds the value of the "mapped_model" field.
	MappedModel string `json:"mapped_model,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestedCount holds the value of the "requested_count" field.
	RequestedCount int `json:"requested_count,omitempty"`
	// CompletedCount holds the value of the "completed_count" field.
	CompletedCount int `json:"completed_count,omitempty"`
	// Request holds the value of the "request" field.
	Request json.RawMessage `json:"request,omitempty"`
	// RequestDigest holds the value of the "request_digest" field.
	RequestDigest string `json:"request_digest,omitempty"`
	// IdempotencyKeyHash holds the value of the "idempotency_key_hash" field.
	IdempotencyKeyHash *string `json:"idempotency_key_hash,omitempty"`
	// ReservedUsd holds the value of the "reserved_usd" field.
	ReservedUsd float64 `json:"reserved_usd,omitempty"`
	// ReservationBillingType holds the value of the "reservation_billing_type" field.
	ReservationBillingType int `json:"reservation_billing_type,omitempty"`
	// ReservationSubscriptionID holds the value of the "reservation_subscription_id" field.
	ReservationSubscriptionID *int64 `json:"reservation_subscription_id,omitempty"`
	// ReservationStatus holds the value of the "reservation_status" field.
	ReservationStatus string `json:"reservation_status,omitempty"`
	// Usage holds the value of the "usage" field.
	Usage json.RawMessage `json:"usage,omitempty"`
	// SettlementStatus holds the value of the "settlement_status" field.
	SettlementStatus string `json:"settlement_status,omitempty"`
	// AttemptID holds the value of the "attempt_id" field.
	AttemptID *string `json:"attempt_id,omitempty"`
	// WorkerID holds the value of the "worker_id" field.
	WorkerID *string `json:"worker_id,omitempty"`
	// ExecutionPhase holds the value of the "execution_phase" field.
	ExecutionPhase string `json:"execution_phase,omitempty"`
	// HeartbeatAt holds the value of the "heartbeat_at" field.
	HeartbeatAt *time.Time `json:"heartbeat_at,omitempty"`
	// CancelRequestedAt holds the value of the "cancel_requested_at" field.
	CancelRequestedAt *time.Time `json:"cancel_requested_at,omitempty"`
	// CanceledAt holds the value of the "canceled_at" field.
	CanceledAt *time.Time `json:"canceled_at,omitempty"`
	// ErrorType holds the value of the "error_type" field.
	ErrorType *string `json:"error_type,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ErrorRetryable holds the value of the "error_retryable" field.
	ErrorRetryable bool `json:"error_retryable,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageJobQuery when eager-loading is set.
	Edges        ImageJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageJobEdges holds the relations/edges for other nodes in the graph.
type ImageJobEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Inputs holds the value of the inputs edge.
	Inputs []*ImageJobInput `json:"inputs,omitempty"`
	// Results holds the value of the results edge.
	Results []*ImageJobResult `json:"results,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageJobEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageJobEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageJobEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// InputsOrErr returns the Inputs value or an error if the edge
// was not loaded in eager-loading.
func (e ImageJobEdges) InputsOrErr() ([]*ImageJobInput, error) {
	if e.loadedTypes[3] {
		return e.Inputs, nil
	}
	return nil, &NotLoadedError{edge: "inputs"}
}

// ResultsOrErr returns the Results value or an error if the edge
// was not loaded in eager-loading.
func (e ImageJobEdges) ResultsOrErr() ([]*ImageJobResult, error) {
	if e.loadedTypes[4] {
		return e.Results, nil
	}
	return nil, &NotLoadedError{edge: "results"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagejob.FieldRequest, imagejob.FieldUsage:
			values[i] = new([]byte)
		case imagejob.FieldErrorRetryable:
			values[i] = new(sql.NullBool)
		case imagejob.FieldReservedUsd:
			values[i] = new(sql.NullFloat64)
		case imagejob.FieldID, imagejob.FieldUserID, imagejob.FieldAPIKeyID, imagejob.FieldGroupID, imagejob.FieldRequestedCount, imagejob.FieldCompletedCount, imagejob.FieldReservationBillingType, imagejob.FieldReservationSubscriptionID:
			values[i] = new(sql.NullInt64)
		case imagejob.FieldPublicID, imagejob.FieldEndpoint, imagejob.FieldOperation, imagejob.FieldMode, imagejob.FieldRequestedModel, imagejob.FieldMappedModel, imagejob.FieldStatus, imagejob.FieldRequestDigest, imagejob.FieldIdempotencyKeyHash, imagejob.FieldReservationStatus, imagejob.FieldSettlementStatus, imagejob.FieldAttemptID, imagejob.FieldWorkerID, imagejob.FieldExecutionPhase, imagejob.FieldErrorType, imagejob.FieldErrorCode, imagejob.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case imagejob.FieldCreatedAt, imagejob.FieldUpdatedAt, imagejob.FieldHeartbeatAt, imagejob.FieldCancelRequestedAt, imagejob.FieldCanceledAt, imagejob.FieldStartedAt, imagejob.FieldFinishedAt, imagejob.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageJob fields.
func (_m *ImageJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagejob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagejob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagejob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagejob.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case imagejob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case imagejob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case imagejob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case imagejob.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case imagejob.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case imagejob.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case imagejob.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case imagejob.FieldMappedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mapped_model", values[i])
			} else if value.Valid {
				_m.MappedModel = value.String
			}
		case imagejob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imagejob.FieldRequestedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_count", values[i])
			} else if value.Valid {
				_m.RequestedCount = int(value.Int64)
			}
		case imagejob.FieldCompletedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_count", values[i])
			} else if value.Valid {
				_m.CompletedCount = int(value.Int64)
			}
		case imagejob.FieldRequest:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Request); err != nil {
					return fmt.Errorf("unmarshal field request: %w", err)
				}
			}
		case imagejob.FieldRequestDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_digest", values[i])
			} else if value.Valid {
				_m.RequestDigest = value.String
			}
		case imagejob.FieldIdempotencyKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key_hash", values[i])
			} else if value.Valid {
				_m.IdempotencyKeyHash = new(string)
				*_m.IdempotencyKeyHash = value.String
			}
		case imagejob.FieldReservedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_usd", values[i])
			} else if value.Valid {
				_m.ReservedUsd = value.Float64
			}
		case imagejob.FieldReservationBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_billing_type", values[i])
			} else if value.Valid {
				_m.ReservationBillingType = int(value.Int64)
			}
		case imagejob.FieldReservationSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_subscription_id", values[i])
			} else if value.Valid {
				_m.ReservationSubscriptionID = new(int64)
				*_m.ReservationSubscriptionID = value.Int64
			}
		case imagejob.FieldReservationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_status", values[i])
			} else if value.Valid {
				_m.ReservationStatus = value.String
			}
		case imagejob.FieldUsage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field usage", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Usage); err != nil {
					return fmt.Errorf("unmarshal field usage: %w", err)
				}
			}
		case imagejob.FieldSettlementStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_status", values[i])
			} else if value.Valid {
				_m.SettlementStatus = value.String
			}
		case imagejob.FieldAttemptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_id", values[i])
			} else if value.Valid {
				_m.AttemptID = new(string)
				*_m.AttemptID = value.String
			}
		case imagejob.FieldWorkerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = new(string)
				*_m.WorkerID = value.String
			}
		case imagejob.FieldExecutionPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_phase", values[i])
			} else if value.Valid {
				_m.ExecutionPhase = value.String
			}
		case imagejob.FieldHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field heartbeat_at", values[i])
			} else if value.Valid {
				_m.HeartbeatAt = new(time.Time)
				*_m.HeartbeatAt = value.Time
			}
		case imagejob.FieldCancelRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_requested_at", values[i])
			} else if value.Valid {
				_m.CancelRequestedAt = new(time.Time)
				*_m.CancelRequestedAt = value.Time
			}
		case imagejob.FieldCanceledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field canceled_at", values[i])
			} else if value.Valid {
				_m.CanceledAt = new(time.Time)
				*_m.CanceledAt = value.Time
			}
		case imagejob.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				_m.ErrorType = new(string)
				*_m.ErrorType = value.String
			}
		case imagejob.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case imagejob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case imagejob.FieldErrorRetryable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field error_retryable", values[i])
			} else if value.Valid {
				_m.ErrorRetryable = value.Bool
			}
		case imagejob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case imagejob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case imagejob.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageJob.
// This includes values selected through modifiers, order, etc.
func (_m *ImageJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ImageJob entity.
func (_m *ImageJob) QueryUser() *UserQuery {
	return NewImageJobClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the ImageJob entity.
func (_m *ImageJob) QueryAPIKey() *APIKeyQuery {
	return NewImageJobClient(_m.config).QueryAPIKey(_m)
}

// QueryGroup queries the "group" edge of the ImageJob entity.
func (_m *ImageJob) QueryGroup() *GroupQuery {
	return NewImageJobClient(_m.config).QueryGroup(_m)
}

// QueryInputs queries the "inputs" edge of the ImageJob entity.
func (_m *ImageJob) QueryInputs() *ImageJobInputQuery {
	return NewImageJobClient(_m.config).QueryInputs(_m)
}

// QueryResults queries the "results" edge of the ImageJob entity.
func (_m *ImageJob) QueryResults() *ImageJobResultQuery {
	return NewImageJobClient(_m.config).QueryResults(_m)
}

// Update returns a builder for updating this ImageJob.
// Note that you need to call ImageJob.Unwrap() before calling this method if this ImageJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageJob) Update() *ImageJobUpdateOne {
	return NewImageJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageJob) Unwrap() *ImageJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageJob) String() string {
	var builder strings.Builder
	builder.WriteString("ImageJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("mapped_model=")
	builder.WriteString(_m.MappedModel)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("requested_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedCount))
	builder.WriteString(", ")
	builder.WriteString("completed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedCount))
	builder.WriteString(", ")
	builder.WriteString("request=")
	builder.WriteString(fmt.Sprintf("%v", _m.Request))
	builder.WriteString(", ")
	builder.WriteString("request_digest=")
	builder.WriteString(_m.RequestDigest)
	builder.WriteString(", ")
	if v := _m.IdempotencyKeyHash; v != nil {
		builder.WriteString("idempotency_key_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reserved_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedUsd))
	builder.WriteString(", ")
	builder.WriteString("reservation_billing_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservationBillingType))
	builder.WriteString(", ")
	if v := _m.ReservationSubscriptionID; v != nil {
		builder.WriteString("reservation_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reservation_status=")
	builder.WriteString(_m.ReservationStatus)
	builder.WriteString(", ")
	builder.WriteString("usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Usage))
	builder.WriteString(", ")
	builder.WriteString("settlement_status=")
	builder.WriteString(_m.SettlementStatus)
	builder.WriteString(", ")
	if v := _m.AttemptID; v != nil {
		builder.WriteString("attempt_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.WorkerID; v != nil {
		builder.WriteString("worker_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("execution_phase=")
	builder.WriteString(_m.ExecutionPhase)
	builder.WriteString(", ")
	if v := _m.HeartbeatAt; v != nil {
		builder.WriteString("heartbeat_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelRequestedAt; v != nil {
		builder.WriteString("cancel_requested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CanceledAt; v != nil {
		builder.WriteString("canceled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorType; v != nil {
		builder.WriteString("error_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("error_retryable=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorRetryable))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageJobs is a parsable slice of ImageJob.
type ImageJobs []*ImageJob
