// Code generated by ent, DO NOT EDIT.

package imagejob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imagejob type in the database.
	Label = "image_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldMappedModel holds the string denoting the mapped_model field in the database.
	FieldMappedModel = "mapped_model"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRequestedCount holds the string denoting the requested_count field in the database.
	FieldRequestedCount = "requested_count"
	// FieldCompletedCount holds the string denoting the completed_count field in the database.
	FieldCompletedCount = "completed_count"
	// FieldRequest holds the string denoting the request field in the database.
	FieldRequest = "request"
	// FieldRequestDigest holds the string denoting the request_digest field in the database.
	FieldRequestDigest = "request_digest"
	// FieldIdempotencyKeyHash holds the string denoting the idempotency_key_hash field in the database.
	FieldIdempotencyKeyHash = "idempotency_key_hash"
	// FieldReservedUsd holds the string denoting the reserved_usd field in the database.
	FieldReservedUsd = "reserved_usd"
	// FieldReservationBillingType holds the string denoting the reservation_billing_type field in the database.
	FieldReservationBillingType = "reservation_billing_type"
	// FieldReservationSubscriptionID holds the string denoting the reservation_subscription_id field in the database.
	FieldReservationSubscriptionID = "reservation_subscription_id"
	// FieldReservationStatus holds the string denoting the reservation_status field in the database.
	FieldReservationStatus = "reservation_status"
	// FieldUsage holds the string denoting the usage field in the database.
	FieldUsage = "usage"
	// FieldSettlementStatus holds the string denoting the settlement_status field in the database.
	FieldSettlementStatus = "settlement_status"
	// FieldAttemptID holds the string denoting the attempt_id field in the database.
	FieldAttemptID = "attempt_id"
	// FieldWorkerID holds the string denoting the worker_id field in the database.
	FieldWorkerID = "worker_id"
	// FieldExecutionPhase holds the string denoting the execution_phase field in the database.
	FieldExecutionPhase = "execution_phase"
	// FieldHeartbeatAt holds the string denoting the heartbeat_at field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldCancelRequestedAt holds the string denoting the cancel_requested_at field in the database.
	FieldCancelRequestedAt = "cancel_requested_at"
	// FieldCanceledAt holds the string denoting the canceled_at field in the database.
	FieldCanceledAt = "canceled_at"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldErrorRetryable holds the string denoting the error_retryable field in the database.
	FieldErrorRetryable = "error_retryable"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeInputs holds the string denoting the inputs edge name in mutations.
	EdgeInputs = "inputs"
	// EdgeResults holds the string denoting the results edge name in mutations.
	EdgeResults = "results"
	// Table holds the table name of the imagejob in the database.
	Table = "image_jobs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "image_jobs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "image_jobs"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "image_jobs"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// InputsTable is the table that holds the inputs relation/edge.
	InputsTable = "image_job_inputs"
	// InputsInverseTable is the table name for the ImageJobInput entity.
	// It exists in this package in order to avoid circular dependency with the "imagejobinput" package.
	InputsInverseTable = "image_job_inputs"
	// InputsColumn is the table column denoting the inputs relation/edge.
	InputsColumn = "job_id"
	// ResultsTable is the table that holds the results relation/edge.
	ResultsTable = "image_job_results"
	// ResultsInverseTable is the table name for the ImageJobResult entity.
	// It exists in this package in order to avoid circular dependency with the "imagejobresult" package.
	ResultsInverseTable = "image_job_results"
	// ResultsColumn is the table column denoting the results relation/edge.
	ResultsColumn = "job_id"
)

// Columns holds all SQL columns for imagejob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldEndpoint,
	FieldOperation,
	FieldMode,
	FieldRequestedModel,
	FieldMappedModel,
	FieldStatus,
	FieldRequestedCount,
	FieldCompletedCount,
	FieldRequest,
	FieldRequestDigest,
	FieldIdempotencyKeyHash,
	FieldReservedUsd,
	FieldReservationBillingType,
	FieldReservationSubscriptionID,
	FieldReservationStatus,
	FieldUsage,
	FieldSettlementStatus,
	FieldAttemptID,
	FieldWorkerID,
	FieldExecutionPhase,
	FieldHeartbeatAt,
	FieldCancelRequestedAt,
	FieldCanceledAt,
	FieldErrorType,
	FieldErrorCode,
	FieldErrorMessage,
	FieldErrorRetryable,
	FieldStartedAt,
	FieldFinishedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// DefaultMappedModel holds the default value on creation for the "mapped_model" field.
	DefaultMappedModel string
	// MappedModelValidator is a validator for the "mapped_model" field. It is called by the builders before save.
	MappedModelValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCompletedCount holds the default value on creation for the "completed_count" field.
	DefaultCompletedCount int
	// RequestDigestValidator is a validator for the "request_digest" field. It is called by the builders before save.
	RequestDigestValidator func(string) error
	// IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	IdempotencyKeyHashValidator func(string) error
	// DefaultReservedUsd holds the default value on creation for the "reserved_usd" field.
	DefaultReservedUsd float64
	// DefaultReservationBillingType holds the default value on creation for the "reservation_billing_type" field.
	DefaultReservationBillingType int
	// DefaultReservationStatus holds the default value on creation for the "reservation_status" field.
	DefaultReservationStatus string
	// ReservationStatusValidator is a validator for the "reservation_status" field. It is called by the builders before save.
	ReservationStatusValidator func(string) error
	// DefaultSettlementStatus holds the default value on creation for the "settlement_status" field.
	DefaultSettlementStatus string
	// SettlementStatusValidator is a validator for the "settlement_status" field. It is called by the builders before save.
	SettlementStatusValidator func(string) error
	// AttemptIDValidator is a validator for the "attempt_id" field. It is called by the builders before save.
	AttemptIDValidator func(string) error
	// WorkerIDValidator is a validator for the "worker_id" field. It is called by the builders before save.
	WorkerIDValidator func(string) error
	// DefaultExecutionPhase holds the default value on creation for the "execution_phase" field.
	DefaultExecutionPhase string
	// ExecutionPhaseValidator is a validator for the "execution_phase" field. It is called by the builders before save.
	ExecutionPhaseValidator func(string) error
	// ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	ErrorTypeValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultErrorRetryable holds the default value on creation for the "error_retryable" field.
	DefaultErrorRetryable bool
)

// OrderOption defines the ordering options for the ImageJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByMappedModel orders the results by the mapped_model field.
func ByMappedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMappedModel, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRequestedCount orders the results by the requested_count field.
func ByRequestedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedCount, opts...).ToFunc()
}

// ByCompletedCount orders the results by the completed_count field.
func ByCompletedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedCount, opts...).ToFunc()
}

// ByRequestDigest orders the results by the request_digest field.
func ByRequestDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestDigest, opts...).ToFunc()
}

// ByIdempotencyKeyHash orders the results by the idempotency_key_hash field.
func ByIdempotencyKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKeyHash, opts...).ToFunc()
}

// ByReservedUsd orders the results by the reserved_usd field.
func ByReservedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedUsd, opts...).ToFunc()
}

// ByReservationBillingType orders the results by the reservation_billing_type field.
func ByReservationBillingType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationBillingType, opts...).ToFunc()
}

// ByReservationSubscriptionID orders the results by the reservation_subscription_id field.
func ByReservationSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationSubscriptionID, opts...).ToFunc()
}

// ByReservationStatus orders the results by the reservation_status field.
func ByReservationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationStatus, opts...).ToFunc()
}

// BySettlementStatus orders the results by the settlement_status field.
func BySettlementStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementStatus, opts...).ToFunc()
}

// ByAttemptID orders the results by the attempt_id field.
func ByAttemptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptID, opts...).ToFunc()
}

// ByWorkerID orders the results by the worker_id field.
func ByWorkerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerID, opts...).ToFunc()
}

// ByExecutionPhase orders the results by the execution_phase field.
func ByExecutionPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionPhase, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeat_at field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByCancelRequestedAt orders the results by the cancel_requested_at field.
func ByCancelRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelRequestedAt, opts...).ToFunc()
}

// ByCanceledAt orders the results by the canceled_at field.
func ByCanceledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanceledAt, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByErrorRetryable orders the results by the error_retryable field.
func ByErrorRetryable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorRetryable, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByInputsCount orders the results by inputs count.
func ByInputsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInputsStep(), opts...)
	}
}

// ByInputs orders the results by inputs terms.
func ByInputs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInputsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResultsCount orders the results by results count.
func ByResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResultsStep(), opts...)
	}
}

// ByResults orders the results by results terms.
func ByResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, APIKeyTable, APIKeyColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newInputsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InputsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InputsTable, InputsColumn),
	)
}
func newResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
	)
}
