// Code generated by ent, DO NOT EDIT.

package imagejob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldPublicID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldGroupID, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldEndpoint, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldOperation, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldMode, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestedModel, v))
}

// MappedModel applies equality check predicate on the "mapped_model" field. It's identical to MappedModelEQ.
func MappedModel(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldMappedModel, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldStatus, v))
}

// RequestedCount applies equality check predicate on the "requested_count" field. It's identical to RequestedCountEQ.
func RequestedCount(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestedCount, v))
}

// CompletedCount applies equality check predicate on the "completed_count" field. It's identical to CompletedCountEQ.
func CompletedCount(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCompletedCount, v))
}

// RequestDigest applies equality check predicate on the "request_digest" field. It's identical to RequestDigestEQ.
func RequestDigest(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestDigest, v))
}

// IdempotencyKeyHash applies equality check predicate on the "idempotency_key_hash" field. It's identical to IdempotencyKeyHashEQ.
func IdempotencyKeyHash(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldIdempotencyKeyHash, v))
}

// ReservedUsd applies equality check predicate on the "reserved_usd" field. It's identical to ReservedUsdEQ.
func ReservedUsd(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservedUsd, v))
}

// ReservationBillingType applies equality check predicate on the "reservation_billing_type" field. It's identical to ReservationBillingTypeEQ.
func ReservationBillingType(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationBillingType, v))
}

// ReservationSubscriptionID applies equality check predicate on the "reservation_subscription_id" field. It's identical to ReservationSubscriptionIDEQ.
func ReservationSubscriptionID(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationSubscriptionID, v))
}

// ReservationStatus applies equality check predicate on the "reservation_status" field. It's identical to ReservationStatusEQ.
func ReservationStatus(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationStatus, v))
}

// SettlementStatus applies equality check predicate on the "settlement_status" field. It's identical to SettlementStatusEQ.
func SettlementStatus(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldSettlementStatus, v))
}

// AttemptID applies equality check predicate on the "attempt_id" field. It's identical to AttemptIDEQ.
func AttemptID(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldAttemptID, v))
}

// WorkerID applies equality check predicate on the "worker_id" field. It's identical to WorkerIDEQ.
func WorkerID(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldWorkerID, v))
}

// ExecutionPhase applies equality check predicate on the "execution_phase" field. It's identical to ExecutionPhaseEQ.
func ExecutionPhase(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldExecutionPhase, v))
}

// HeartbeatAt applies equality check predicate on the "heartbeat_at" field. It's identical to HeartbeatAtEQ.
func HeartbeatAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldHeartbeatAt, v))
}

// CancelRequestedAt applies equality check predicate on the "cancel_requested_at" field. It's identical to CancelRequestedAtEQ.
func CancelRequestedAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCancelRequestedAt, v))
}

// CanceledAt applies equality check predicate on the "canceled_at" field. It's identical to CanceledAtEQ.
func CanceledAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCanceledAt, v))
}

// ErrorType applies equality check predicate on the "error_type" field. It's identical to ErrorTypeEQ.
func ErrorType(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorType, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorRetryable applies equality check predicate on the "error_retryable" field. It's identical to ErrorRetryableEQ.
func ErrorRetryable(v bool) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorRetryable, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldFinishedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldPublicID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldGroupID, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldEndpoint, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldOperation, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldMode, v))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldRequestedModel, v))
}

// MappedModelEQ applies the EQ predicate on the "mapped_model" field.
func MappedModelEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldMappedModel, v))
}

// MappedModelNEQ applies the NEQ predicate on the "mapped_model" field.
func MappedModelNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldMappedModel, v))
}

// MappedModelIn applies the In predicate on the "mapped_model" field.
func MappedModelIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldMappedModel, vs...))
}

// MappedModelNotIn applies the NotIn predicate on the "mapped_model" field.
func MappedModelNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldMappedModel, vs...))
}

// MappedModelGT applies the GT predicate on the "mapped_model" field.
func MappedModelGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldMappedModel, v))
}

// MappedModelGTE applies the GTE predicate on the "mapped_model" field.
func MappedModelGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldMappedModel, v))
}

// MappedModelLT applies the LT predicate on the "mapped_model" field.
func MappedModelLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldMappedModel, v))
}

// MappedModelLTE applies the LTE predicate on the "mapped_model" field.
func MappedModelLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldMappedModel, v))
}

// MappedModelContains applies the Contains predicate on the "mapped_model" field.
func MappedModelContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldMappedModel, v))
}

// MappedModelHasPrefix applies the HasPrefix predicate on the "mapped_model" field.
func MappedModelHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldMappedModel, v))
}

// MappedModelHasSuffix applies the HasSuffix predicate on the "mapped_model" field.
func MappedModelHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldMappedModel, v))
}

// MappedModelEqualFold applies the EqualFold predicate on the "mapped_model" field.
func MappedModelEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldMappedModel, v))
}

// MappedModelContainsFold applies the ContainsFold predicate on the "mapped_model" field.
func MappedModelContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldMappedModel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldStatus, v))
}

// RequestedCountEQ applies the EQ predicate on the "requested_count" field.
func RequestedCountEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestedCount, v))
}

// RequestedCountNEQ applies the NEQ predicate on the "requested_count" field.
func RequestedCountNEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldRequestedCount, v))
}

// RequestedCountIn applies the In predicate on the "requested_count" field.
func RequestedCountIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldRequestedCount, vs...))
}

// RequestedCountNotIn applies the NotIn predicate on the "requested_count" field.
func RequestedCountNotIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldRequestedCount, vs...))
}

// RequestedCountGT applies the GT predicate on the "requested_count" field.
func RequestedCountGT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldRequestedCount, v))
}

// RequestedCountGTE applies the GTE predicate on the "requested_count" field.
func RequestedCountGTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldRequestedCount, v))
}

// RequestedCountLT applies the LT predicate on the "requested_count" field.
func RequestedCountLT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldRequestedCount, v))
}

// RequestedCountLTE applies the LTE predicate on the "requested_count" field.
func RequestedCountLTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldRequestedCount, v))
}

// CompletedCountEQ applies the EQ predicate on the "completed_count" field.
func CompletedCountEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCompletedCount, v))
}

// CompletedCountNEQ applies the NEQ predicate on the "completed_count" field.
func CompletedCountNEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldCompletedCount, v))
}

// CompletedCountIn applies the In predicate on the "completed_count" field.
func CompletedCountIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldCompletedCount, vs...))
}

// CompletedCountNotIn applies the NotIn predicate on the "completed_count" field.
func CompletedCountNotIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldCompletedCount, vs...))
}

// CompletedCountGT applies the GT predicate on the "completed_count" field.
func CompletedCountGT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldCompletedCount, v))
}

// CompletedCountGTE applies the GTE predicate on the "completed_count" field.
func CompletedCountGTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldCompletedCount, v))
}

// CompletedCountLT applies the LT predicate on the "completed_count" field.
func CompletedCountLT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldCompletedCount, v))
}

// CompletedCountLTE applies the LTE predicate on the "completed_count" field.
func CompletedCountLTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldCompletedCount, v))
}

// RequestDigestEQ applies the EQ predicate on the "request_digest" field.
func RequestDigestEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldRequestDigest, v))
}

// RequestDigestNEQ applies the NEQ predicate on the "request_digest" field.
func RequestDigestNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldRequestDigest, v))
}

// RequestDigestIn applies the In predicate on the "request_digest" field.
func RequestDigestIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldRequestDigest, vs...))
}

// RequestDigestNotIn applies the NotIn predicate on the "request_digest" field.
func RequestDigestNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldRequestDigest, vs...))
}

// RequestDigestGT applies the GT predicate on the "request_digest" field.
func RequestDigestGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldRequestDigest, v))
}

// RequestDigestGTE applies the GTE predicate on the "request_digest" field.
func RequestDigestGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldRequestDigest, v))
}

// RequestDigestLT applies the LT predicate on the "request_digest" field.
func RequestDigestLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldRequestDigest, v))
}

// RequestDigestLTE applies the LTE predicate on the "request_digest" field.
func RequestDigestLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldRequestDigest, v))
}

// RequestDigestContains applies the Contains predicate on the "request_digest" field.
func RequestDigestContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldRequestDigest, v))
}

// RequestDigestHasPrefix applies the HasPrefix predicate on the "request_digest" field.
func RequestDigestHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldRequestDigest, v))
}

// RequestDigestHasSuffix applies the HasSuffix predicate on the "request_digest" field.
func RequestDigestHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldRequestDigest, v))
}

// RequestDigestEqualFold applies the EqualFold predicate on the "request_digest" field.
func RequestDigestEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldRequestDigest, v))
}

// RequestDigestContainsFold applies the ContainsFold predicate on the "request_digest" field.
func RequestDigestContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldRequestDigest, v))
}

// IdempotencyKeyHashEQ applies the EQ predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashNEQ applies the NEQ predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashIn applies the In predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldIdempotencyKeyHash, vs...))
}

// IdempotencyKeyHashNotIn applies the NotIn predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldIdempotencyKeyHash, vs...))
}

// IdempotencyKeyHashGT applies the GT predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashGTE applies the GTE predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashLT applies the LT predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashLTE applies the LTE predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashContains applies the Contains predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashHasPrefix applies the HasPrefix predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashHasSuffix applies the HasSuffix predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashIsNil applies the IsNil predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldIdempotencyKeyHash))
}

// IdempotencyKeyHashNotNil applies the NotNil predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldIdempotencyKeyHash))
}

// IdempotencyKeyHashEqualFold applies the EqualFold predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashContainsFold applies the ContainsFold predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldIdempotencyKeyHash, v))
}

// ReservedUsdEQ applies the EQ predicate on the "reserved_usd" field.
func ReservedUsdEQ(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservedUsd, v))
}

// ReservedUsdNEQ applies the NEQ predicate on the "reserved_usd" field.
func ReservedUsdNEQ(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldReservedUsd, v))
}

// ReservedUsdIn applies the In predicate on the "reserved_usd" field.
func ReservedUsdIn(vs ...float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldReservedUsd, vs...))
}

// ReservedUsdNotIn applies the NotIn predicate on the "reserved_usd" field.
func ReservedUsdNotIn(vs ...float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldReservedUsd, vs...))
}

// ReservedUsdGT applies the GT predicate on the "reserved_usd" field.
func ReservedUsdGT(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldReservedUsd, v))
}

// ReservedUsdGTE applies the GTE predicate on the "reserved_usd" field.
func ReservedUsdGTE(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldReservedUsd, v))
}

// ReservedUsdLT applies the LT predicate on the "reserved_usd" field.
func ReservedUsdLT(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldReservedUsd, v))
}

// ReservedUsdLTE applies the LTE predicate on the "reserved_usd" field.
func ReservedUsdLTE(v float64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldReservedUsd, v))
}

// ReservationBillingTypeEQ applies the EQ predicate on the "reservation_billing_type" field.
func ReservationBillingTypeEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationBillingType, v))
}

// ReservationBillingTypeNEQ applies the NEQ predicate on the "reservation_billing_type" field.
func ReservationBillingTypeNEQ(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldReservationBillingType, v))
}

// ReservationBillingTypeIn applies the In predicate on the "reservation_billing_type" field.
func ReservationBillingTypeIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldReservationBillingType, vs...))
}

// ReservationBillingTypeNotIn applies the NotIn predicate on the "reservation_billing_type" field.
func ReservationBillingTypeNotIn(vs ...int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldReservationBillingType, vs...))
}

// ReservationBillingTypeGT applies the GT predicate on the "reservation_billing_type" field.
func ReservationBillingTypeGT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldReservationBillingType, v))
}

// ReservationBillingTypeGTE applies the GTE predicate on the "reservation_billing_type" field.
func ReservationBillingTypeGTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldReservationBillingType, v))
}

// ReservationBillingTypeLT applies the LT predicate on the "reservation_billing_type" field.
func ReservationBillingTypeLT(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldReservationBillingType, v))
}

// ReservationBillingTypeLTE applies the LTE predicate on the "reservation_billing_type" field.
func ReservationBillingTypeLTE(v int) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldReservationBillingType, v))
}

// ReservationSubscriptionIDEQ applies the EQ predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDNEQ applies the NEQ predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDNEQ(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDIn applies the In predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldReservationSubscriptionID, vs...))
}

// ReservationSubscriptionIDNotIn applies the NotIn predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDNotIn(vs ...int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldReservationSubscriptionID, vs...))
}

// ReservationSubscriptionIDGT applies the GT predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDGT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDGTE applies the GTE predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDGTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDLT applies the LT predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDLT(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDLTE applies the LTE predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDLTE(v int64) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldReservationSubscriptionID, v))
}

// ReservationSubscriptionIDIsNil applies the IsNil predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldReservationSubscriptionID))
}

// ReservationSubscriptionIDNotNil applies the NotNil predicate on the "reservation_subscription_id" field.
func ReservationSubscriptionIDNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldReservationSubscriptionID))
}

// ReservationStatusEQ applies the EQ predicate on the "reservation_status" field.
func ReservationStatusEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldReservationStatus, v))
}

// ReservationStatusNEQ applies the NEQ predicate on the "reservation_status" field.
func ReservationStatusNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldReservationStatus, v))
}

// ReservationStatusIn applies the In predicate on the "reservation_status" field.
func ReservationStatusIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldReservationStatus, vs...))
}

// ReservationStatusNotIn applies the NotIn predicate on the "reservation_status" field.
func ReservationStatusNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldReservationStatus, vs...))
}

// ReservationStatusGT applies the GT predicate on the "reservation_status" field.
func ReservationStatusGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldReservationStatus, v))
}

// ReservationStatusGTE applies the GTE predicate on the "reservation_status" field.
func ReservationStatusGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldReservationStatus, v))
}

// ReservationStatusLT applies the LT predicate on the "reservation_status" field.
func ReservationStatusLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldReservationStatus, v))
}

// ReservationStatusLTE applies the LTE predicate on the "reservation_status" field.
func ReservationStatusLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldReservationStatus, v))
}

// ReservationStatusContains applies the Contains predicate on the "reservation_status" field.
func ReservationStatusContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldReservationStatus, v))
}

// ReservationStatusHasPrefix applies the HasPrefix predicate on the "reservation_status" field.
func ReservationStatusHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldReservationStatus, v))
}

// ReservationStatusHasSuffix applies the HasSuffix predicate on the "reservation_status" field.
func ReservationStatusHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldReservationStatus, v))
}

// ReservationStatusEqualFold applies the EqualFold predicate on the "reservation_status" field.
func ReservationStatusEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldReservationStatus, v))
}

// ReservationStatusContainsFold applies the ContainsFold predicate on the "reservation_status" field.
func ReservationStatusContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldReservationStatus, v))
}

// UsageIsNil applies the IsNil predicate on the "usage" field.
func UsageIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldUsage))
}

// UsageNotNil applies the NotNil predicate on the "usage" field.
func UsageNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldUsage))
}

// SettlementStatusEQ applies the EQ predicate on the "settlement_status" field.
func SettlementStatusEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldSettlementStatus, v))
}

// SettlementStatusNEQ applies the NEQ predicate on the "settlement_status" field.
func SettlementStatusNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldSettlementStatus, v))
}

// SettlementStatusIn applies the In predicate on the "settlement_status" field.
func SettlementStatusIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldSettlementStatus, vs...))
}

// SettlementStatusNotIn applies the NotIn predicate on the "settlement_status" field.
func SettlementStatusNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldSettlementStatus, vs...))
}

// SettlementStatusGT applies the GT predicate on the "settlement_status" field.
func SettlementStatusGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldSettlementStatus, v))
}

// SettlementStatusGTE applies the GTE predicate on the "settlement_status" field.
func SettlementStatusGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldSettlementStatus, v))
}

// SettlementStatusLT applies the LT predicate on the "settlement_status" field.
func SettlementStatusLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldSettlementStatus, v))
}

// SettlementStatusLTE applies the LTE predicate on the "settlement_status" field.
func SettlementStatusLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldSettlementStatus, v))
}

// SettlementStatusContains applies the Contains predicate on the "settlement_status" field.
func SettlementStatusContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldSettlementStatus, v))
}

// SettlementStatusHasPrefix applies the HasPrefix predicate on the "settlement_status" field.
func SettlementStatusHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldSettlementStatus, v))
}

// SettlementStatusHasSuffix applies the HasSuffix predicate on the "settlement_status" field.
func SettlementStatusHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldSettlementStatus, v))
}

// SettlementStatusEqualFold applies the EqualFold predicate on the "settlement_status" field.
func SettlementStatusEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldSettlementStatus, v))
}

// SettlementStatusContainsFold applies the ContainsFold predicate on the "settlement_status" field.
func SettlementStatusContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldSettlementStatus, v))
}

// AttemptIDEQ applies the EQ predicate on the "attempt_id" field.
func AttemptIDEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldAttemptID, v))
}

// AttemptIDNEQ applies the NEQ predicate on the "attempt_id" field.
func AttemptIDNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldAttemptID, v))
}

// AttemptIDIn applies the In predicate on the "attempt_id" field.
func AttemptIDIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldAttemptID, vs...))
}

// AttemptIDNotIn applies the NotIn predicate on the "attempt_id" field.
func AttemptIDNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldAttemptID, vs...))
}

// AttemptIDGT applies the GT predicate on the "attempt_id" field.
func AttemptIDGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldAttemptID, v))
}

// AttemptIDGTE applies the GTE predicate on the "attempt_id" field.
func AttemptIDGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldAttemptID, v))
}

// AttemptIDLT applies the LT predicate on the "attempt_id" field.
func AttemptIDLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldAttemptID, v))
}

// AttemptIDLTE applies the LTE predicate on the "attempt_id" field.
func AttemptIDLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldAttemptID, v))
}

// AttemptIDContains applies the Contains predicate on the "attempt_id" field.
func AttemptIDContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldAttemptID, v))
}

// AttemptIDHasPrefix applies the HasPrefix predicate on the "attempt_id" field.
func AttemptIDHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldAttemptID, v))
}

// AttemptIDHasSuffix applies the HasSuffix predicate on the "attempt_id" field.
func AttemptIDHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldAttemptID, v))
}

// AttemptIDIsNil applies the IsNil predicate on the "attempt_id" field.
func AttemptIDIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldAttemptID))
}

// AttemptIDNotNil applies the NotNil predicate on the "attempt_id" field.
func AttemptIDNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldAttemptID))
}

// AttemptIDEqualFold applies the EqualFold predicate on the "attempt_id" field.
func AttemptIDEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldAttemptID, v))
}

// AttemptIDContainsFold applies the ContainsFold predicate on the "attempt_id" field.
func AttemptIDContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldAttemptID, v))
}

// WorkerIDEQ applies the EQ predicate on the "worker_id" field.
func WorkerIDEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldWorkerID, v))
}

// WorkerIDNEQ applies the NEQ predicate on the "worker_id" field.
func WorkerIDNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldWorkerID, v))
}

// WorkerIDIn applies the In predicate on the "worker_id" field.
func WorkerIDIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldWorkerID, vs...))
}

// WorkerIDNotIn applies the NotIn predicate on the "worker_id" field.
func WorkerIDNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldWorkerID, vs...))
}

// WorkerIDGT applies the GT predicate on the "worker_id" field.
func WorkerIDGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldWorkerID, v))
}

// WorkerIDGTE applies the GTE predicate on the "worker_id" field.
func WorkerIDGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldWorkerID, v))
}

// WorkerIDLT applies the LT predicate on the "worker_id" field.
func WorkerIDLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldWorkerID, v))
}

// WorkerIDLTE applies the LTE predicate on the "worker_id" field.
func WorkerIDLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldWorkerID, v))
}

// WorkerIDContains applies the Contains predicate on the "worker_id" field.
func WorkerIDContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldWorkerID, v))
}

// WorkerIDHasPrefix applies the HasPrefix predicate on the "worker_id" field.
func WorkerIDHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldWorkerID, v))
}

// WorkerIDHasSuffix applies the HasSuffix predicate on the "worker_id" field.
func WorkerIDHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldWorkerID, v))
}

// WorkerIDIsNil applies the IsNil predicate on the "worker_id" field.
func WorkerIDIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldWorkerID))
}

// WorkerIDNotNil applies the NotNil predicate on the "worker_id" field.
func WorkerIDNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldWorkerID))
}

// WorkerIDEqualFold applies the EqualFold predicate on the "worker_id" field.
func WorkerIDEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldWorkerID, v))
}

// WorkerIDContainsFold applies the ContainsFold predicate on the "worker_id" field.
func WorkerIDContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldWorkerID, v))
}

// ExecutionPhaseEQ applies the EQ predicate on the "execution_phase" field.
func ExecutionPhaseEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldExecutionPhase, v))
}

// ExecutionPhaseNEQ applies the NEQ predicate on the "execution_phase" field.
func ExecutionPhaseNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldExecutionPhase, v))
}

// ExecutionPhaseIn applies the In predicate on the "execution_phase" field.
func ExecutionPhaseIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldExecutionPhase, vs...))
}

// ExecutionPhaseNotIn applies the NotIn predicate on the "execution_phase" field.
func ExecutionPhaseNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldExecutionPhase, vs...))
}

// ExecutionPhaseGT applies the GT predicate on the "execution_phase" field.
func ExecutionPhaseGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldExecutionPhase, v))
}

// ExecutionPhaseGTE applies the GTE predicate on the "execution_phase" field.
func ExecutionPhaseGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldExecutionPhase, v))
}

// ExecutionPhaseLT applies the LT predicate on the "execution_phase" field.
func ExecutionPhaseLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldExecutionPhase, v))
}

// ExecutionPhaseLTE applies the LTE predicate on the "execution_phase" field.
func ExecutionPhaseLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldExecutionPhase, v))
}

// ExecutionPhaseContains applies the Contains predicate on the "execution_phase" field.
func ExecutionPhaseContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldExecutionPhase, v))
}

// ExecutionPhaseHasPrefix applies the HasPrefix predicate on the "execution_phase" field.
func ExecutionPhaseHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldExecutionPhase, v))
}

// ExecutionPhaseHasSuffix applies the HasSuffix predicate on the "execution_phase" field.
func ExecutionPhaseHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldExecutionPhase, v))
}

// ExecutionPhaseEqualFold applies the EqualFold predicate on the "execution_phase" field.
func ExecutionPhaseEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldExecutionPhase, v))
}

// ExecutionPhaseContainsFold applies the ContainsFold predicate on the "execution_phase" field.
func ExecutionPhaseContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldExecutionPhase, v))
}

// HeartbeatAtEQ applies the EQ predicate on the "heartbeat_at" field.
func HeartbeatAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtNEQ applies the NEQ predicate on the "heartbeat_at" field.
func HeartbeatAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtIn applies the In predicate on the "heartbeat_at" field.
func HeartbeatAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtNotIn applies the NotIn predicate on the "heartbeat_at" field.
func HeartbeatAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtGT applies the GT predicate on the "heartbeat_at" field.
func HeartbeatAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldHeartbeatAt, v))
}

// HeartbeatAtGTE applies the GTE predicate on the "heartbeat_at" field.
func HeartbeatAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldHeartbeatAt, v))
}

// HeartbeatAtLT applies the LT predicate on the "heartbeat_at" field.
func HeartbeatAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldHeartbeatAt, v))
}

// HeartbeatAtLTE applies the LTE predicate on the "heartbeat_at" field.
func HeartbeatAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldHeartbeatAt, v))
}

// HeartbeatAtIsNil applies the IsNil predicate on the "heartbeat_at" field.
func HeartbeatAtIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldHeartbeatAt))
}

// HeartbeatAtNotNil applies the NotNil predicate on the "heartbeat_at" field.
func HeartbeatAtNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldHeartbeatAt))
}

// CancelRequestedAtEQ applies the EQ predicate on the "cancel_requested_at" field.
func CancelRequestedAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCancelRequestedAt, v))
}

// CancelRequestedAtNEQ applies the NEQ predicate on the "cancel_requested_at" field.
func CancelRequestedAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldCancelRequestedAt, v))
}

// CancelRequestedAtIn applies the In predicate on the "cancel_requested_at" field.
func CancelRequestedAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldCancelRequestedAt, vs...))
}

// CancelRequestedAtNotIn applies the NotIn predicate on the "cancel_requested_at" field.
func CancelRequestedAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldCancelRequestedAt, vs...))
}

// CancelRequestedAtGT applies the GT predicate on the "cancel_requested_at" field.
func CancelRequestedAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldCancelRequestedAt, v))
}

// CancelRequestedAtGTE applies the GTE predicate on the "cancel_requested_at" field.
func CancelRequestedAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldCancelRequestedAt, v))
}

// CancelRequestedAtLT applies the LT predicate on the "cancel_requested_at" field.
func CancelRequestedAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldCancelRequestedAt, v))
}

// CancelRequestedAtLTE applies the LTE predicate on the "cancel_requested_at" field.
func CancelRequestedAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldCancelRequestedAt, v))
}

// CancelRequestedAtIsNil applies the IsNil predicate on the "cancel_requested_at" field.
func CancelRequestedAtIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldCancelRequestedAt))
}

// CancelRequestedAtNotNil applies the NotNil predicate on the "cancel_requested_at" field.
func CancelRequestedAtNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldCancelRequestedAt))
}

// CanceledAtEQ applies the EQ predicate on the "canceled_at" field.
func CanceledAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldCanceledAt, v))
}

// CanceledAtNEQ applies the NEQ predicate on the "canceled_at" field.
func CanceledAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldCanceledAt, v))
}

// CanceledAtIn applies the In predicate on the "canceled_at" field.
func CanceledAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldCanceledAt, vs...))
}

// CanceledAtNotIn applies the NotIn predicate on the "canceled_at" field.
func CanceledAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldCanceledAt, vs...))
}

// CanceledAtGT applies the GT predicate on the "canceled_at" field.
func CanceledAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldCanceledAt, v))
}

// CanceledAtGTE applies the GTE predicate on the "canceled_at" field.
func CanceledAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldCanceledAt, v))
}

// CanceledAtLT applies the LT predicate on the "canceled_at" field.
func CanceledAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldCanceledAt, v))
}

// CanceledAtLTE applies the LTE predicate on the "canceled_at" field.
func CanceledAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldCanceledAt, v))
}

// CanceledAtIsNil applies the IsNil predicate on the "canceled_at" field.
func CanceledAtIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldCanceledAt))
}

// CanceledAtNotNil applies the NotNil predicate on the "canceled_at" field.
func CanceledAtNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldCanceledAt))
}

// ErrorTypeEQ applies the EQ predicate on the "error_type" field.
func ErrorTypeEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorType, v))
}

// ErrorTypeNEQ applies the NEQ predicate on the "error_type" field.
func ErrorTypeNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldErrorType, v))
}

// ErrorTypeIn applies the In predicate on the "error_type" field.
func ErrorTypeIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldErrorType, vs...))
}

// ErrorTypeNotIn applies the NotIn predicate on the "error_type" field.
func ErrorTypeNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldErrorType, vs...))
}

// ErrorTypeGT applies the GT predicate on the "error_type" field.
func ErrorTypeGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldErrorType, v))
}

// ErrorTypeGTE applies the GTE predicate on the "error_type" field.
func ErrorTypeGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldErrorType, v))
}

// ErrorTypeLT applies the LT predicate on the "error_type" field.
func ErrorTypeLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldErrorType, v))
}

// ErrorTypeLTE applies the LTE predicate on the "error_type" field.
func ErrorTypeLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldErrorType, v))
}

// ErrorTypeContains applies the Contains predicate on the "error_type" field.
func ErrorTypeContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldErrorType, v))
}

// ErrorTypeHasPrefix applies the HasPrefix predicate on the "error_type" field.
func ErrorTypeHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldErrorType, v))
}

// ErrorTypeHasSuffix applies the HasSuffix predicate on the "error_type" field.
func ErrorTypeHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldErrorType, v))
}

// ErrorTypeIsNil applies the IsNil predicate on the "error_type" field.
func ErrorTypeIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldErrorType))
}

// ErrorTypeNotNil applies the NotNil predicate on the "error_type" field.
func ErrorTypeNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldErrorType))
}

// ErrorTypeEqualFold applies the EqualFold predicate on the "error_type" field.
func ErrorTypeEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldErrorType, v))
}

// ErrorTypeContainsFold applies the ContainsFold predicate on the "error_type" field.
func ErrorTypeContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldErrorType, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ErrorRetryableEQ applies the EQ predicate on the "error_retryable" field.
func ErrorRetryableEQ(v bool) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldErrorRetryable, v))
}

// ErrorRetryableNEQ applies the NEQ predicate on the "error_retryable" field.
func ErrorRetryableNEQ(v bool) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldErrorRetryable, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotNull(FieldFinishedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ImageJob {
	return predicate.ImageJob(sql.FieldLTE(FieldExpiresAt, v))
}

// HasInputs applies the HasEdge predicate on the "inputs" edge.
func HasInputs() predicate.ImageJob {
	return predicate.ImageJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InputsTable, InputsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInputsWith applies the HasEdge predicate on the "inputs" edge with a given conditions (other predicates).
func HasInputsWith(preds ...predicate.ImageJobInput) predicate.ImageJob {
	return predicate.ImageJob(func(s *sql.Selector) {
		step := newInputsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResults applies the HasEdge predicate on the "results" edge.
func HasResults() predicate.ImageJob {
	return predicate.ImageJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResultsWith applies the HasEdge predicate on the "results" edge with a given conditions (other predicates).
func HasResultsWith(preds ...predicate.ImageJobResult) predicate.ImageJob {
	return predicate.ImageJob(func(s *sql.Selector) {
		step := newResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageJob) predicate.ImageJob {
	return predicate.ImageJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageJob) predicate.ImageJob {
	return predicate.ImageJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageJob) predicate.ImageJob {
	return predicate.ImageJob(sql.NotPredicates(p))
}
